### ISSUE TITLE
Just little inaccuracy in installation process

### ISSUE THREAD

**Issue by KMiNT21** [home-assistant/home-assistant.github.io#10482]
1) Scripts path 
2) Python modules aiohttp_cors and sqlalchemy

Config: Debian 10, Python 3.7.3, fish shell

----------------------------------------------------

```sh
@debian ~> pip3 install homeassistant
...
...

Successfully installed MarkupSafe-1.1.1 PyJWT-1.7.1 aiohttp-3.5.4 astral-1.10.1 async-timeout-3.0.1 attrs-19.1.0 bcrypt-3.1.7 certifi-2019.9.11 cffi-1.12.3 cryptography-2.7 homeassistant-0.99.3 importlib-metadata-0.19 jinja2-2.10.1 more-itertools-7.2.0 multidict-4.5.2 pycparser-2.19 python-slugify-3.0.3 pytz-2019.2 pyyaml-5.1.2 requests-2.22.0 ruamel.yaml-0.15.100 text-unidecode-1.2 voluptuous-0.11.7 voluptuous-serialize-2.2.0 yarl-1.3.0 zipp-0.6.0

@debian ~> hass --open-ui
fish: Unknown command hass

```

May be change line in documentation to
`~/.local/bin/hass --open-ui` ? Or add something about PATH...

```sh
@debian ~> hass --open-ui
...
...
ModuleNotFoundError: No module named 'aiohttp_cors'
...
ModuleNotFoundError: No module named 'sqlalchemy'
...


```

So had to install these modules by 
`pip3 install aiohttp_cors sqlalchemy`

**Comment by frenck** [comment]
You didn't create a virtual env?

**Comment by KMiNT21** [comment]
No.

**Comment by frenck** [comment]
Well, that might be the cause of the issue (the path thing for sure).
All our documentation is guiding through the venv process (unless it isn't, in that case, I would love to know which part you did follow and is missing this information).

**Comment by springstan** [comment]
@KMiNT21 have you just followed the steps on the 'Get started section':
> To get started:
> 
> `python3 -m pip install homeassistant`
> `hass --open-ui`

on the [home-assistant github page](https://github.com/home-assistant/home-assistant#home-assistant-)?

@frenck Since a virtual environment is not listed as a requirement in these instructions.

**Comment by frenck** [comment]
Check, will make sure that will be taken away, we have you manual on https://www.home-assistant.io

**Comment by larry-tx** [comment]
I wish that was all there was to it. After following the manual installation process to the letter down to copying and pasting the commands with the venv installation, this is what I get:
```
  Config directory: /home/homeassistant/.homeassistant
2019-11-13 16:59:58 INFO (SyncWorker_2) [homeassistant.loader] Loaded group from homeassistant.components.group
2019-11-13 16:59:58 INFO (SyncWorker_1) [homeassistant.loader] Loaded script from homeassistant.components.script
2019-11-13 16:59:58 INFO (SyncWorker_0) [homeassistant.loader] Loaded default_config from homeassistant.components.default_config
2019-11-13 16:59:58 INFO (SyncWorker_4) [homeassistant.loader] Loaded tts from homeassistant.components.tts
2019-11-13 16:59:58 INFO (SyncWorker_1) [homeassistant.loader] Loaded automation from homeassistant.components.automation
2019-11-13 16:59:58 INFO (SyncWorker_2) [homeassistant.loader] Loaded homeassistant from homeassistant.components.homeassistant
2019-11-13 16:59:58 INFO (SyncWorker_0) [homeassistant.loader] Loaded persistent_notification from homeassistant.components.persistent_notification
2019-11-13 16:59:58 INFO (SyncWorker_6) [homeassistant.loader] Loaded http from homeassistant.components.http
2019-11-13 16:59:58 INFO (SyncWorker_3) [homeassistant.loader] Loaded device_automation from homeassistant.components.device_automation
2019-11-13 16:59:58 INFO (MainThread) [homeassistant.setup] Setting up homeassistant
2019-11-13 16:59:58 INFO (MainThread) [homeassistant.setup] Setup of domain homeassistant took 0.0 seconds.
2019-11-13 16:59:58 INFO (MainThread) [homeassistant.setup] Setting up persistent_notification
2019-11-13 16:59:58 INFO (MainThread) [homeassistant.setup] Setup of domain persistent_notification took 0.0 seconds.
2019-11-13 16:59:58 INFO (SyncWorker_7) [homeassistant.loader] Loaded webhook from homeassistant.components.webhook
2019-11-13 16:59:58 INFO (SyncWorker_1) [homeassistant.loader] Loaded cloud from homeassistant.components.cloud
2019-11-13 16:59:58 INFO (SyncWorker_4) [homeassistant.loader] Loaded config from homeassistant.components.config
2019-11-13 16:59:58 INFO (SyncWorker_0) [homeassistant.loader] Loaded frontend from homeassistant.components.frontend
2019-11-13 16:59:58 INFO (SyncWorker_3) [homeassistant.loader] Loaded api from homeassistant.components.api
2019-11-13 16:59:58 INFO (SyncWorker_5) [homeassistant.loader] Loaded auth from homeassistant.components.auth
2019-11-13 16:59:58 INFO (SyncWorker_8) [homeassistant.loader] Loaded lovelace from homeassistant.components.lovelace
2019-11-13 16:59:58 INFO (SyncWorker_2) [homeassistant.loader] Loaded onboarding from homeassistant.components.onboarding
2019-11-13 16:59:58 INFO (SyncWorker_6) [homeassistant.loader] Loaded system_log from homeassistant.components.system_log
2019-11-13 16:59:58 INFO (SyncWorker_9) [homeassistant.loader] Loaded websocket_api from homeassistant.components.websocket_api
2019-11-13 16:59:58 INFO (SyncWorker_7) [homeassistant.loader] Loaded history from homeassistant.components.history
2019-11-13 16:59:58 INFO (SyncWorker_1) [homeassistant.loader] Loaded recorder from homeassistant.components.recorder
2019-11-13 16:59:58 INFO (SyncWorker_4) [homeassistant.loader] Loaded logbook from homeassistant.components.logbook
2019-11-13 16:59:58 INFO (SyncWorker_0) [homeassistant.loader] Loaded map from homeassistant.components.map
2019-11-13 16:59:58 INFO (SyncWorker_3) [homeassistant.loader] Loaded mobile_app from homeassistant.components.mobile_app
2019-11-13 16:59:58 INFO (SyncWorker_5) [homeassistant.loader] Loaded person from homeassistant.components.person
2019-11-13 16:59:58 INFO (SyncWorker_8) [homeassistant.loader] Loaded ssdp from homeassistant.components.ssdp
2019-11-13 16:59:58 INFO (SyncWorker_2) [homeassistant.loader] Loaded sun from homeassistant.components.sun
2019-11-13 16:59:58 INFO (SyncWorker_6) [homeassistant.loader] Loaded system_health from homeassistant.components.system_health
2019-11-13 16:59:58 INFO (SyncWorker_9) [homeassistant.loader] Loaded updater from homeassistant.components.updater
2019-11-13 16:59:58 INFO (SyncWorker_7) [homeassistant.loader] Loaded zeroconf from homeassistant.components.zeroconf
2019-11-13 16:59:58 INFO (MainThread) [homeassistant.bootstrap] Setting up {'system_log'}
2019-11-13 16:59:58 INFO (MainThread) [homeassistant.setup] Setting up http
2019-11-13 16:59:58 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.0 seconds.
2019-11-13 16:59:58 INFO (MainThread) [homeassistant.setup] Setting up system_log
2019-11-13 16:59:58 INFO (MainThread) [homeassistant.setup] Setup of domain system_log took 0.0 seconds.
2019-11-13 16:59:58 INFO (MainThread) [homeassistant.setup] Setting up recorder
2019-11-13 16:59:58 INFO (MainThread) [homeassistant.setup] Setup of domain recorder took 0.1 seconds.
2019-11-13 16:59:58 INFO (MainThread) [homeassistant.setup] Setting up updater
2019-11-13 16:59:58 INFO (MainThread) [homeassistant.setup] Setup of domain updater took 0.0 seconds.
2019-11-13 16:59:58 INFO (MainThread) [homeassistant.setup] Setting up sun
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setup of domain sun took 0.1 seconds.
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setting up lovelace
2019-11-13 16:59:59 ERROR (MainThread) [homeassistant.setup] Error during setup of component lovelace
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 172, in _async_setup_component
    hass, processed_config
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/lovelace/__init__.py", line 66, in async_setup
    hass.components.frontend.async_register_built_in_panel(
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 421, in __getattr__
    component: Optional[ModuleType] = integration.get_component()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 223, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/frontend/__init__.py", line 10, in <module>
    import hass_frontend
ModuleNotFoundError: No module named 'hass_frontend'
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setting up group
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setup of domain group took 0.0 seconds.
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setting up person
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setting up ssdp
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setup of domain ssdp took 0.0 seconds.
2019-11-13 16:59:59 INFO (SyncWorker_5) [homeassistant.loader] Loaded binary_sensor from homeassistant.components.binary_sensor
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setting up webhook
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setup of domain webhook took 0.0 seconds.
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setting up system_health
2019-11-13 16:59:59 INFO (SyncWorker_1) [homeassistant.loader] Loaded google_translate from homeassistant.components.google_translate
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setup of domain system_health took 0.0 seconds.
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setting up history
2019-11-13 16:59:59 ERROR (MainThread) [homeassistant.setup] Error during setup of component history
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 172, in _async_setup_component
    hass, processed_config
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/history/__init__.py", line 283, in async_setup
    hass.components.frontend.async_register_built_in_panel(
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 421, in __getattr__
    component: Optional[ModuleType] = integration.get_component()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 223, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/frontend/__init__.py", line 10, in <module>
    import hass_frontend
ModuleNotFoundError: No module named 'hass_frontend'
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setting up script
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setup of domain script took 0.0 seconds.
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setting up auth
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.0 seconds.
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setting up api
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setting up config
2019-11-13 16:59:59 ERROR (MainThread) [homeassistant.setup] Error during setup of component config
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/setup.py", line 172, in _async_setup_component
    hass, processed_config
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/config/__init__.py", line 34, in async_setup
    hass.components.frontend.async_register_built_in_panel(
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 421, in __getattr__
    component: Optional[ModuleType] = integration.get_component()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 223, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/frontend/__init__.py", line 10, in <module>
    import hass_frontend
ModuleNotFoundError: No module named 'hass_frontend'
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setting up websocket_api
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setup of domain websocket_api took 0.0 seconds.
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setting up binary_sensor
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setup of domain binary_sensor took 0.0 seconds.
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setup of domain person took 0.5 seconds.
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setting up tts
2019-11-13 16:59:59 INFO (MainThread) [homeassistant.setup] Setup of domain api took 0.1 seconds.
2019-11-13 17:00:00 INFO (MainThread) [homeassistant.setup] Setting up cloud
2019-11-13 17:00:00 INFO (MainThread) [homeassistant.setup] Setting up device_automation
2019-11-13 17:00:00 INFO (MainThread) [homeassistant.setup] Setup of domain device_automation took 0.0 seconds.
2019-11-13 17:00:00 INFO (MainThread) [homeassistant.setup] Setting up onboarding
2019-11-13 17:00:00 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.updater
2019-11-13 17:00:00 INFO (MainThread) [homeassistant.setup] Setting up zeroconf
2019-11-13 17:00:00 INFO (MainThread) [homeassistant.setup] Setting up automation
2019-11-13 17:00:00 INFO (MainThread) [homeassistant.setup] Setup of domain automation took 0.0 seconds.
2019-11-13 17:00:00 INFO (MainThread) [homeassistant.setup] Setup of domain tts took 1.3 seconds.
2019-11-13 17:00:00 INFO (MainThread) [homeassistant.setup] Setup of domain cloud took 0.1 seconds.
2019-11-13 17:00:00 INFO (MainThread) [homeassistant.setup] Setup of domain onboarding took 0.2 seconds.
2019-11-13 17:00:00 INFO (SyncWorker_6) [homeassistant.loader] Loaded hue from homeassistant.components.hue
2019-11-13 17:00:01 ERROR (MainThread) [homeassistant.setup] Setup failed for mobile_app: Unable to import component
2019-11-13 17:00:01 INFO (MainThread) [homeassistant.setup] Setup of domain zeroconf took 0.2 seconds.
2019-11-13 17:00:01 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of frontend. Setup failed for dependencies: lovelace
2019-11-13 17:00:01 ERROR (MainThread) [homeassistant.setup] Setup failed for frontend: Could not set up all dependencies.
2019-11-13 17:00:01 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of logbook. Setup failed for dependencies: frontend
2019-11-13 17:00:01 ERROR (MainThread) [homeassistant.setup] Setup failed for logbook: Could not set up all dependencies.
2019-11-13 17:00:01 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of map. Setup failed for dependencies: frontend
2019-11-13 17:00:01 ERROR (MainThread) [homeassistant.setup] Setup failed for map: Could not set up all dependencies.
2019-11-13 17:00:01 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of default_config. Setup failed for dependencies: config, frontend, history, logbook, map, mobile_app
2019-11-13 17:00:01 ERROR (MainThread) [homeassistant.setup] Setup failed for default_config: Could not set up all dependencies.
2019-11-13 17:00:01 INFO (MainThread) [homeassistant.components.hue] Invalid authentication for 192.168.1.111, requesting link.
2019-11-13 17:00:03 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 5.39s
2019-11-13 17:00:03 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2019-11-13 17:00:03 INFO (MainThread) [homeassistant.core] Timer:starting
2019-11-13 17:00:03 INFO (SyncWorker_8) [homeassistant.components.zeroconf] Starting Zeroconf broadcast
```
Seems like a pretty defective product. Oh well, after spending four days trying to get this to work, I'm worn out and down, totally disgusted. If you've got a very quick fix, I'd like to hear it. Otherwise, I'm exploring openHAB.

**Comment by frenck** [comment]
This is a known issue: https://github.com/home-assistant/home-assistant/issues/28361

Workaround is to install the `hass_frontend` dependency manually.

**Comment by frenck** [comment]
Wow totally forgot this issue was still open.

The specific instruction has been removed from that location 👍

**Comment by HendrikVE** [comment]
I just followed the documentation [here](https://www.home-assistant.io/installation/linux#install-home-assistant-core). I still had to run `pip3 install aiohttp_cors` in order to get home assistant running because this dependency was missing. Should be added to the guide.

**Comment by frenck** [comment]
that doesn't sound right and a bug. Adding workaround to the documentation is not a solution.

Furthermore, this issue is closed for over a year. Please just create a new one, nothing is here is recent to matter.
