### ISSUE TITLE
Problems with PS4 after upgrading 0.105.4

### ISSUE THREAD

**Issue by sxx1314** [home-assistant/home-assistant.github.io#12097]
Remove the ps4 device and re-add the prompt unkonw error.

```
2020-02-15 16:54:14 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/mnt/mmc0/work/homeassistant/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/mnt/mmc0/work/homeassistant/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/mnt/mmc0/work/homeassistant/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/mnt/mmc0/work/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/mnt/mmc0/work/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/mnt/mmc0/work/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/mnt/mmc0/work/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/mnt/mmc0/work/homeassistant/lib/python3.8/site-packages/homeassistant/components/config/config_entries.py", line 160, in post
    return await super().post(request, flow_id)
  File "/mnt/mmc0/work/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/mnt/mmc0/work/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/data_entry_flow.py", line 89, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/mnt/mmc0/work/homeassistant/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 130, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/mnt/mmc0/work/homeassistant/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/mnt/mmc0/work/homeassistant/lib/python3.8/site-packages/homeassistant/components/ps4/config_flow.py", line 70, in async_step_creds
    self.creds = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt/mmc0/work/homeassistant/lib/python3.8/site-packages/pyps4_2ndscreen/helpers.py", line 79, in get_creds
    credentials = Credentials(device_name)
  File "/mnt/mmc0/work/homeassistant/lib/python3.8/site-packages/pyps4_2ndscreen/credential.py", line 43, in __init__
    self.start()
  File "/mnt/mmc0/work/homeassistant/lib/python3.8/site-packages/pyps4_2ndscreen/credential.py", line 54, in start
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
OSError: [Errno 92] Protocol not available
```

**Comment by frenck** [comment]
Hi there @sxx1314!

Thanks for opening up an issue, however, this is the issue tracker for our website. If you experience issues with Home Assistant, please open up an issue here:

<https://github.com/home-assistant/home-assistant/issues> 

Please be sure to search first, if it is a known issue, there might be an issue created already.

Thanks! 👍
