### ISSUE TITLE
Add info on VLC telnet integration (prerequisites to avoid issue with the volume set)

### ISSUE THREAD

**Issue by alessio-papi** [home-assistant/home-assistant.github.io#14297]
## Unable to set volume on VLC through telnet client to VLC "misconfiguration"

Hi,

I'm using VLC through telnet client in order to manage it with HA.
I found that the set of volume was not working and I was going to open a bug on it, but I found that error it's not strictly related to HA.

Let me explain: on volume set using media player I got:

	Logger: homeassistant.components.websocket_api.http.connection.1591737312
	Source: components/vlc_telnet/media_player.py:223
	Integration: Home Assistant WebSocket API (documentation, issues)
	First occurred: 16:43:38 (9 occurrences)
	Last logged: 17:58:39

	Error in `volume 300.0' lua/modules/common.lua:175: bad argument #1 to 'set' (number expected, got string)
	Error in `volume 65.0' lua/modules/common.lua:175: bad argument #1 to 'set' (number expected, got string)
	Error in `volume 500.0' lua/modules/common.lua:175: bad argument #1 to 'set' (number expected, got string)
	Error in `volume 95.0' lua/modules/common.lua:175: bad argument #1 to 'set' (number expected, got string)
	Error in `volume 330.0' lua/modules/common.lua:175: bad argument #1 to 'set' (number expected, got string)
	Traceback (most recent call last):
	  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
	    await hass.services.async_call(
	  File "/usr/src/homeassistant/homeassistant/core.py", line 1308, in async_call
	    task.result()
	  File "/usr/src/homeassistant/homeassistant/core.py", line 1343, in _execute_service
	    await handler.func(service_call)
	  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
	    await self.hass.helpers.service.entity_service_call(
	  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
	    future.result()  # pop exception if have
	  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in async_request_call
	    await coro
	  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
	    await result
	  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 547, in async_set_volume_level
	    await self.hass.async_add_job(self.set_volume_level, volume)
	  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
	    result = self.fn(*self.args, **self.kwargs)
	  File "/usr/src/homeassistant/homeassistant/components/vlc_telnet/media_player.py", line 223, in set_volume_level
	    self._vlc.set_volume(str(volume * 500))
	  File "/usr/local/lib/python3.8/site-packages/python_telnet_vlc/vlctelnet.py", line 287, in set_volume
	    self.run_command(command)
	  File "/usr/local/lib/python3.8/site-packages/python_telnet_vlc/vlctelnet.py", line 66, in run_command
	    raise LuaError(command_error.group())
	python_telnet_vlc.vlctelnet.LuaError: Error in `volume 140.0' lua/modules/common.lua:175: bad argument #1 to 'set' (number expected, got string)

The numeric value it's correct, but VLC return a parse error.
I discovered that my VLC instance it's running with my local it_IT, and it seems that VLC uses the locale to parse the numbers also in telnet protocol ! 
In Italy the decimal separator is "," not ".".
I tried a simple python snippets and the volume works using "250,0" not "250.0".

I think it's to complex to change the code to manage the locale of the remote VLC, and also should be configured by the user.

If possibile, it's better to add a note in the doc, something like: run VLC using en_US locale in order to have the integration full functional.

Regards
Alessio

**Comment by frenck** [comment]
Feel free to add a note to the documentation. Every page has an edit button at the top.

Thanks for helping out 👍

**Comment by frenck** [comment]
Fixed in #14306, thanks @alessio-papi 👍
