### ISSUE TITLE
server_host  doc confusing

### ISSUE THREAD

**Issue by bbrendon** [home-assistant/home-assistant.github.io#14531]
Below is the text from the docs. The default is 0.0.0.0 which it says is ipv4/ipv6 but then it says to set it to 0.0.0.0 to be only ipv4? Seems like something is amiss there as it describes 0.0.0.0 two different ways. I would fix it but I don't know what the correction would be. Maybe the default is 0.0.0.0 and ::/0 ?

https://www.home-assistant.io/integrations/http/#server_host

server_host list | string(optional, default: 0.0.0.0)
Only listen to incoming requests on specific IP/host. By default the http integration will accept all IPv4 and IPv6 connections. Use server_host: 0.0.0.0 if you want to only listen to IPv4 addresses.

**Comment by frenck** [comment]
default is auto detect ipv4+ipv6, that needs to be adjusted indeed.

**Comment by bbrendon** [comment]
Okay. I’ll submit a pr

**Comment by bbrendon** [comment]
Looks like I found a bug? Setting to ipv6 only, provides the below. Config is default except ipv4 is disabled.

```
@ha  /tmp/ha  sudo netstat -tulpn|grep 8234                                                  
tcp6       0      0 :::8234                 :::*                    LISTEN      12081/python3
@ha  /tmp/ha  cat home-assistant.log              
2020-09-19 11:15:10 ERROR (MainThread) [homeassistant.setup] Error during setup of component tts
Traceback (most recent call last):
  File "/tmp/ha/venv/lib/python3.7/site-packages/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/tmp/ha/venv/lib/python3.7/site-packages/homeassistant/components/tts/__init__.py", line 119, in async_setup
    base_url = conf.get(CONF_BASE_URL) or get_url(hass)
  File "/tmp/ha/venv/lib/python3.7/site-packages/homeassistant/helpers/network.py", line 59, in get_url
    require_standard_port=require_standard_port,
  File "/tmp/ha/venv/lib/python3.7/site-packages/homeassistant/helpers/network.py", line 150, in _get_internal_url
    require_standard_port=require_standard_port,
  File "/tmp/ha/venv/lib/python3.7/site-packages/homeassistant/helpers/network.py", line 257, in _get_deprecated_base_url
    base_url = yarl.URL(hass.config.api.deprecated_base_url)
  File "/tmp/ha/venv/lib/python3.7/site-packages/yarl/__init__.py", line 158, in __new__
    raise ValueError("Invalid URL: host is required for absolute urls")
ValueError: Invalid URL: host is required for absolute urls
2020-09-19 11:15:10 ERROR (MainThread) [homeassistant.setup] Error during setup of component zeroconf
Traceback (most recent call last):
  File "/tmp/ha/venv/lib/python3.7/site-packages/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/ha/venv/lib/python3.7/site-packages/homeassistant/components/zeroconf/__init__.py", line 172, in setup
    params["external_url"] = get_url(hass, allow_internal=False)
  File "/tmp/ha/venv/lib/python3.7/site-packages/homeassistant/helpers/network.py", line 73, in get_url
    require_standard_port=require_standard_port,
  File "/tmp/ha/venv/lib/python3.7/site-packages/homeassistant/helpers/network.py", line 214, in _get_external_url
    require_standard_port=require_standard_port,
  File "/tmp/ha/venv/lib/python3.7/site-packages/homeassistant/helpers/network.py", line 257, in _get_deprecated_base_url
    base_url = yarl.URL(hass.config.api.deprecated_base_url)
  File "/tmp/ha/venv/lib/python3.7/site-packages/yarl/__init__.py", line 158, in __new__
    raise ValueError("Invalid URL: host is required for absolute urls")
ValueError: Invalid URL: host is required for absolute urls
2020-09-19 11:15:10 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of default_config. Setup failed for dependencies: zeroconf
2020-09-19 11:15:10 ERROR (MainThread) [homeassistant.setup] Setup failed for default_config: Could not set up all dependencies.
```

**Comment by bbrendon** [comment]
For the PR. This is the default. server_port obviously removed.

```
http:
  server_port: 8234
  server_host:
    - "0.0.0.0"
    - "::"
```
