### ISSUE TITLE
Error while setting up platform synology

### ISSUE THREAD

**Issue by cuihaijun** [home-assistant/home-assistant.github.io#1504]
16-11-27 07:18:33 homeassistant.components.camera: Error while setting up platform synology
Traceback (most recent call last):
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 145, in _async_setup_platform
    entity_platform.async_add_entities, discovery_info
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/components/camera/synology.py", line 118, in async_setup_platform
    syno_auth_url
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/components/camera/synology.py", line 206, in get_session_id
    return auth_resp['data']['sid']
KeyError: 'data'

**Comment by Landrash** [comment]
This is the repository for the Home Assistant documentation.  Have a look a the main repo for issues and complement this with the requested information.

**Comment by cuihaijun** [comment]
Home Assistant 0.33.2
#configuration.yaml#

camera:
  - platform: synology
    url: https://192.168.1.10:5001
    username: admin
    password: 9807067
    verify_ssl: false

**Comment by cuihaijun** [comment]
![came](https://cloud.githubusercontent.com/assets/10826652/20646741/597ef9c0-b4bc-11e6-8cab-419e20dc1259.png)

**Comment by Landrash** [comment]
It's still in the wrong repository.

**Comment by cuihaijun** [comment]
I'm sorry, I English is not good, you want me to provide any error log file?

**Comment by Landrash** [comment]
@cuihaijun Nope. Post your issue here -> https://github.com/home-assistant/home-assistant/issues .
