### ISSUE TITLE
asuswrt device tracking is not working fine.... in HA version: 2020.12.2

### ISSUE THREAD

**Issue by plutosherry** [home-assistant/home-assistant.github.io#16099]
unfortunate，The issue is still there..... HA version: 2020.12.2
asuswrt device tracking is not working fine.....
and there is error logs:

> 
Error during setup of component asuswrt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/src/homeassistant/homeassistant/components/asuswrt/__init__.py", line 85, in async_setup
    await api.connection.async_connect()
  File "/usr/local/lib/python3.8/site-packages/aioasuswrt/connection.py", line 77, in async_connect
    self._client = await asyncssh.connect(self._host, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/asyncssh/misc.py", line 182, in __await__
    return (yield from self._coro)
  File "/usr/local/lib/python3.8/site-packages/asyncssh/connection.py", line 5451, in connect
    conn, _ = yield from create_connection(None, host, port, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/asyncssh/connection.py", line 5107, in create_connection
    yield from auth_waiter
asyncssh.misc.DisconnectError: Disconnect Error: Connection lost

_Originally posted by @plutosherry in https://github.com/home-assistant/core/issues/37736#issuecomment-753963282_

**Comment by frenck** [comment]
This is an issue with an Home Assistant Core integration and not related to the documentation.

Please file your issue here:

<https://github.com/home-assistant/core/issues>

Thanks 👍
