### ISSUE TITLE
integration broken with core 2021.2.0 ?

### ISSUE THREAD

**Issue by hilikstein** [home-assistant/home-assistant.github.io#16415]
After upgrading core to 2021.2.0 today, shelly integration fails to load. it fails inside coap code. I've enabled logger and got the following:
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 127.0.0.1 to multicast 224.0.1.187 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 127.0.0.1 to multicast 224.0.1.188 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 10.0.0.59 to multicast 224.0.1.187 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 10.0.0.59 to multicast 224.0.1.188 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 172.30.32.1 to multicast 224.0.1.187 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 172.30.32.1 to multicast 224.0.1.188 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 172.17.0.1 to multicast 224.0.1.187 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 172.17.0.1 to multicast 224.0.1.188 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 169.254.137.227 to multicast 224.0.1.187 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 169.254.137.227 to multicast 224.0.1.188 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 169.254.37.146 to multicast 224.0.1.187 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 169.254.37.146 to multicast 224.0.1.188 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 169.254.152.140 to multicast 224.0.1.187 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 169.254.152.140 to multicast 224.0.1.188 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 169.254.140.93 to multicast 224.0.1.187 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 169.254.140.93 to multicast 224.0.1.188 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 169.254.27.168 to multicast 224.0.1.187 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 169.254.27.168 to multicast 224.0.1.188 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 169.254.225.60 to multicast 224.0.1.187 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 169.254.225.60 to multicast 224.0.1.188 membership
2021-02-04 16:26:22 DEBUG (MainThread) [aioshelly.coap] Adding ip 169.254.133.176 to multicast 224.0.1.187 membership
2021-02-04 16:26:22 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry shellyswitch25-40F5201790D5 for shelly
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/shelly/__init__.py", line 84, in async_setup_entry
    coap_context = await get_coap_context(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/singleton.py", line 42, in async_wrapped
    result = await func(hass)
  File "/usr/src/homeassistant/homeassistant/components/shelly/__init__.py", line 54, in get_coap_context
    await context.initialize()
  File "/usr/local/lib/python3.8/site-packages/aioshelly/coap.py", line 86, in initialize
    self.sock = socket_init()
  File "/usr/local/lib/python3.8/site-packages/aioshelly/coap.py", line 66, in socket_init
    sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, group)
OSError: [Errno 105] No buffer space available

anything wrong on my end?

**Comment by SeanPM5** [comment]
This repository is for documentation only. To report a bug with an integration please use the core repository here (and make sure to fill out the issue template): https://github.com/home-assistant/core/issues/new/choose

Thanks.
