### ISSUE TITLE
Template Weather Provider forecast_template usage

### ISSUE THREAD

**Issue by aes-alienrip** [home-assistant/home-assistant.github.io#16863]
### Feedback

According to the example :
```
forecast_template: "{{ states.weather.my_region.attributes.forecast }}" 
```
when i try to use openweathermap as the forecast data source :
```
forecast_template: "{{ states.weather.openweathermap.attributes.forecast }}"
```
```
forecast_template: "{{ state_attr('weather.openweathermap', 'forecast') }}"
```
after restart it return error log and no forcast in the weather ui

### URL

https://www.home-assistant.io/integrations/weather.template/

### Version

2021.3.1

```
Logger: homeassistant
Source: components/weather/__init__.py:181
First occurred: 8:44:42 PM (1 occurrences)
Last logged: 8:44:42 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 265, in _async_template_startup
    result_info.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 879, in async_refresh
    self._refresh(None)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1005, in _refresh
    self.hass.async_run_hass_job(self._job, event, updates)
  File "/usr/src/homeassistant/homeassistant/core.py", line 435, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 251, in _handle_results
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 321, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 181, in state_attributes
    forecast_entry = dict(forecast_entry)
ValueError: dictionary update sequence element #0 has length 1; 2 is required

```

**Comment by frenck** [comment]
Hi there @hung2kgithub!

That is a so-called stack trace you have pasted there as an error and is not something that should happen. Please report this as a bug on our core repository:

<https://github.com/home-assistant/core/issues> 

This is not something we can or should solve in the documentation.

**Comment by aes-alienrip** [comment]
Thanks, @frenck
i am newbie and sorry to post in a wrong area.

**Comment by frenck** [comment]
No problem m8!
