### ISSUE TITLE
speedtest notworking after updating home assistant to 2021.4.0

### ISSUE THREAD

**Issue by stolenvw** [home-assistant/home-assistant.github.io#17324]
### Feedback

speedtest fails to load after update to home assistant 

### URL

https://www.home-assistant.io/integrations/speedtestdotnet/

### Version

2021.4.0

`Logger: homeassistant.config_entries
Source: components/speedtestdotnet/__init__.py:194
First occurred: 7:11:40 PM (1 occurrences)
Last logged: 7:11:40 PM

Error setting up entry SpeedTest for speedtestdotnet
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 249, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/speedtestdotnet/__init__.py", line 75, in async_setup_entry
    await coordinator.async_setup()
  File "/usr/src/homeassistant/homeassistant/components/speedtestdotnet/__init__.py", line 194, in async_setup
    self.api = await self.hass.async_add_executor_job(speedtest.Speedtest)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/speedtest.py", line 1091, in __init__
    self.get_config()
  File "/usr/local/lib/python3.8/site-packages/speedtest.py", line 1173, in get_config
    ignore_servers = list(
ValueError: invalid literal for int() with base 10: ''`

**Comment by SeanPM5** [comment]
Appreciate the report, but for future reference bug reports with integrations belong on the "core" repository (this one is just for documentation/website stuff). 

There's an existing issue for the Speedtest integration here: https://github.com/home-assistant/core/issues/48803
