### ISSUE TITLE
MQTT sensor: device config variable doesn't seem to accept "suggested_area"

### ISSUE THREAD

**Issue by nickagian** [home-assistant/home-assistant.github.io#17579]
### Feedback

When trying to create an MQTT device through MQTT discovery, the **suggested_area** doesn't seem to be accepted as a valid entry in the map. Here is the error message I get:

```
Exception in async_discover when dispatching 'mqtt_discovery_new_sensor_mqtt': ({'name': 'testdev_battery', 'device_class': 'battery', 'state_topic': 'homeassistant/sensor/testdev_battery/state', 'unique_id': 'testdev_battery', 'json_attributes_topic': 'homeassistant/sensor/testdev_battery/attributes', 'device': {'name': 'testdev', 'manufacturer': 'me', 'identifiers': 'AA:BB:CC', 'suggested_area': 'Office Room', 'sw_version': '1.0a'}, 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 152, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: extra keys not allowed @ data['device']['suggested_area']
```

If this is indeed is true, I suggest we remove this from the documentation.

### URL

https://www.home-assistant.io/integrations/sensor.mqtt/

### Version

2021.4.6 (using core version core-2021.3.4)

**Comment by emontnemery** [comment]
Suggested area support was added to MQTT in 2021.4, please update your core version.
