### ISSUE TITLE
API issue 

### ISSUE THREAD

**Issue by ckroth14** [home-assistant/home-assistant.github.io#17755]
### Feedback

I found that the "Etekcity 7 Amp US outlet - ESW01-USA (Round)" has an error that pops up at the bottom of HA. Not all outlets will do this and I have 7.  I am in no way capable of fixing the issue in HA but I do know that the devices that dont throw the error are running Firmware version 1.1.27 and the ones that are throwing the error are running 2.125. There doesn't seam to be any differences in the plugs. The entities still work but maybe a little slower. In node-red the the it shows "API-Error". I'm adding my logs below. This Integration is the life blood of my HA. Thanks in advanced  -CK

HA Version
core-2021.5.1

Logger: homeassistant.components.websocket_api.http.connection
Source: components/vesync/common.py:70
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: May 6, 2021, 6:46:32 PM (910 occurrences)
Last logged: 12:25:55 PM

[1660231368] Expecting value: line 1 column 1 (char 0)
[1723281144] Expecting value: line 1 column 1 (char 0)
[1794933352] Expecting value: line 1 column 1 (char 0)
[1795361712] Expecting value: line 1 column 1 (char 0)
[1744760568] Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 167, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 726, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 759, in async_turn_off
    await self.hass.async_add_executor_job(ft.partial(self.turn_off, **kwargs))
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/vesync/common.py", line 70, in turn_off
    self.device.turn_off()
  File "/usr/local/lib/python3.8/site-packages/pyvesync/vesyncoutlet.py", line 239, in turn_off
    _, status_code = Helpers.call_api(
  File "/usr/local/lib/python3.8/site-packages/pyvesync/helpers.py", line 180, in call_api
    response = r.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### URL

https://www.home-assistant.io/integrations/vesync/

### Version

2021.5.1

**Comment by frenck** [comment]
Hi there, @ckroth14 👋 

It seems like you want to report a bug with an Home Assistant integration, however, you've submitted documentation feedback. There is no amount of documentation that I can adjust to fix a bug in Home Assistant 😓 

In case of an issue with an Home Assistant integration, please raise an issue here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍
