### ISSUE TITLE
Template Weather Provider not working

### ISSUE THREAD

**Issue by TTLucian** [home-assistant/home-assistant.github.io#18061]
### Feedback

Template Weather Provider is not working
Config:
```
weather:
  - platform: template
    unique_id: custom
    name: "custom"
    condition_template: "{{ states.weather.home.attributes.forecast }}"
    temperature_template: "{{ states('sensor.custom_temperature_outside') | float}}"
    humidity_template: "{{ states('sensor.custom_humidity_outside')| float }}"
    attribution_template: "Weather provided by custom personal weather station"
    pressure_template: "{{ states('sensor.custom_pressure_inside')| float }}"
    wind_speed_template: "{{ states('sensor.custom_wind_speed')| float }}"
    wind_bearing_template: "{{ states('sensor.custom_wind_direction') }}"
    forecast_template: "{{ states.weather.home.attributes.forecast }}"
```

Error:
```
`ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 268, in _async_template_startup
    result_info.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 873, in async_refresh
    self._refresh(None)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 999, in _refresh
    self.hass.async_run_hass_job(self._job, event, updates)
  File "/usr/src/homeassistant/homeassistant/core.py", line 424, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 250, in _handle_results
    attr.handle_result(
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 92, in handle_result
    validated = self.validator(result)
  File "/usr/src/homeassistant/homeassistant/components/template/weather.py", line 237, in <lambda>
    lambda condition: condition if condition in CONDITION_CLASSES else None,
TypeError: unhashable type: 'Wrapper'`
```

### URL

https://www.home-assistant.io/integrations/weather.template/

### Version

2021.5.5

**Comment by frenck** [comment]
Hi there @TTLucian 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback. Please report issues with integrations in the Core issue tracker:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by TTLucian** [comment]
Ok. Thanks!
