### ISSUE TITLE
Unexpected error during integration Asuswrt

### ISSUE THREAD

**Issue by CharlyLara** [home-assistant/home-assistant.github.io#18098]
### Feedback

Logger: homeassistant.components.asuswrt.config_flow
Source: components/asuswrt/config_flow.py:113
Integration: ASUSWRT (documentation, issues)
First occurred: 23:19:27 (1 occurrences)
Last logged: 23:19:27

Unknown error connecting with AsusWrt router at 
192.168.2.1
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/asuswrt/config_flow.py", line 113, in _async_check_connection
    await api.connection.async_connect()
  File "/usr/local/lib/python3.8/site-packages/aioasuswrt/connection.py", line 77, in async_connect
    self._client = await asyncssh.connect(self._host, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/asyncssh/connection.py", line 6460, in connect
    return await _connect(options.host, options.port, loop, options.tunnel,
  File "/usr/local/lib/python3.8/site-packages/asyncssh/connection.py", line 223, in _connect
    await conn.wait_established()
  File "/usr/local/lib/python3.8/site-packages/asyncssh/connection.py", line 2107, in wait_established
    await self._waiter
asyncssh.misc.PermissionDenied: Permission denied

### URL

https://www.home-assistant.io/integrations/asuswrt/

### Version

2021.6.2

### Additional information

I can't set up the integration. It just says unexpected error

Logger: homeassistant.components.asuswrt.config_flow
Source: components/asuswrt/config_flow.py:113
Integration: ASUSWRT (documentation, issues)
First occurred: 23:19:27 (1 occurrences)
Last logged: 23:19:27

Unknown error connecting with AsusWrt router at 192.168.2.1
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/asuswrt/config_flow.py", line 113, in _async_check_connection
    await api.connection.async_connect()
  File "/usr/local/lib/python3.8/site-packages/aioasuswrt/connection.py", line 77, in async_connect
    self._client = await asyncssh.connect(self._host, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/asyncssh/connection.py", line 6460, in connect
    return await _connect(options.host, options.port, loop, options.tunnel,
  File "/usr/local/lib/python3.8/site-packages/asyncssh/connection.py", line 223, in _connect
    await conn.wait_established()
  File "/usr/local/lib/python3.8/site-packages/asyncssh/connection.py", line 2107, in wait_established
    await self._waiter
asyncssh.misc.PermissionDenied: Permission denied

**Comment by ollo69** [comment]
Check your SSH connection configuration on the router. This error is because the router is not allowing the connection.
