### ISSUE TITLE
Yale Smart Living

### ISSUE THREAD

**Issue by ttjoc** [home-assistant/home-assistant.github.io#18127]
### Feedback

Yale Smart Living stop working after juni version

### URL

https://www.home-assistant.io/integrations/yale_smart_alarm/

### Version

2021.6.3

**Comment by araines** [comment]
I think I’m having the same problem, but I’m not sure if it’s to do with any version change in the software or something has changed at Yale’s end perhaps.

However I do have these in the logs:
```

Logger: homeassistant.helpers.entity
Source: components/yale_smart_alarm/alarm_control_panel.py:97
First occurred: 13 June 2021, 8:56:58 (1138occurrences) 
Last logged: 8:20:57

Update for alarm_control_panel.yale_smart_alarm fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 350, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 566, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/yale_smart_alarm/alarm_control_panel.py", line 97, in update
    armed_status = self._client.get_armed_status()
  File "/usr/local/lib/python3.8/site-packages/yalesmartalarmclient/client.py", line 140, in get_armed_status
    alarm_state = self.auth.get_authenticated(self._ENDPOINT_GET_MODE)
  File "/usr/local/lib/python3.8/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/yalesmartalarmclient/auth.py", line 60, in get_authenticated
    self._authorize()
  File "/usr/local/lib/python3.8/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/yalesmartalarmclient/auth.py", line 118, in _authorize
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://mob.yalehomesystem.co.uk/yapi/yapi/o/token/
```

Which suggests my auth has stopped working or my credentials are bad, but I haven’t changed anything. 

I’ll probably need to do a bit more debugging at some point

**Comment by araines** [comment]
Mine is working fine again now, disregard!
