### ISSUE TITLE
Flexit integration

### ISSUE THREAD

**Issue by Rodahl88** [home-assistant/home-assistant.github.io#18949]
### Feedback

Problem getting the Flexit component to work properly.

Log:
2021-08-16 12:48:30 ERROR (MainThread) [homeassistant.components.climate] Error while setting up flexit platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/flexit/climate.py", line 42, in setup_platform
    hub = hass.data[MODBUS_DOMAIN][config.get(CONF_HUB)]
KeyError: 'Modbushub'

Any workaround here?

### URL

https://www.home-assistant.io/integrations/flexit/

### Version

2021.8.7

**Comment by frenck** [comment]
Hi there @Rodahl88 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. There is no amount of documentation that I can adjust to fix this issue.

Please file issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 
../Frenck
