### ISSUE TITLE
Tank Utility Integration is Outdated?

### ISSUE THREAD

**Issue by Aesop7** [home-assistant/home-assistant.github.io#18953]
### Feedback

Couple points here:

1. Receiving an error when trying to use the documentation for adding Tank Utility:

In my config:

```
sensor:
  - platform: tank_utility
    email: "me@myemail"
    password: "mysupersecretpwd"
    devices:
      - sensor: "sensornumberlike13r4sdb1234rs"
```
I've tried quotes and no quotes for the sensor

And here is the resulting error
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 646, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/tank_utility/sensor.py", line 131, in update
    data = self.get_data()
  File "/usr/src/homeassistant/homeassistant/components/tank_utility/sensor.py", line 112, in get_data
    data = tank_monitor.get_device_data(self._token, self.device)
  File "/usr/local/lib/python3.9/site-packages/tank_utility/device.py", line 31, in get_device_data
    response = requests.get(common.get_api_url(token=token, path="devices/" + device))
TypeError: can only concatenate str (not "collections.OrderedDict") to str
```
2.  Why isn't this included as a default integration when I search via the HASS app?

### URL

https://www.home-assistant.io/integrations/tank_utility/

### Version

2021.8.7

**Comment by frenck** [comment]
Hi there @Aesop7 👋 


It seems like you want to report an issue with an integration, however, you have submitted documentation feedback instead. There is no amount of documentation we can adjust to fix integration issues.

Please report issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
