### ISSUE TITLE
TADO.SET_WATER_HEATER_TIMER - entity_id is not optional

### ISSUE THREAD

**Issue by jccroft1** [home-assistant/home-assistant.github.io#18987]
### Feedback

As stated in subject, in the docs entity_id is listed as optional for TADO.SET_WATER_HEATER_TIMER. However, when not passing entity_id I run into the below error. 

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 359, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1434, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec
    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/helpers/config_validation.py", line 132, in validate
    raise vol.Invalid("must contain at least one of {}.".format(", ".join(keys)))
TypeError: sequence item 0: expected str instance, Optional found
```

### URL

https://www.home-assistant.io/integrations/tado/

### Version

2021.8.7

### Additional information

Server running Home Assistant 2021.4.1.

**Comment by frenck** [comment]
Actually, it is, as alternatively an area or device could be targeted instead of the entity_id
