### ISSUE TITLE
pi_hole service: It looks like `entity_id` is required

### ISSUE THREAD

**Issue by bnordli** [home-assistant/home-assistant.github.io#19047]
### Feedback

I was stumped for a while, because calling `pi_hole.disable` with the example data resulted in `TypeError: sequence item 0: expected str instance, Optional found`. I tried several variations of the `duration` format before realizing the `entity_id` was not filled in automatically.

However, the documentation says that `entity_id` is not required, so either `all` should be set as the default value or the documentation should be updated to `Required: true`.

### URL

https://www.home-assistant.io/integrations/pi_hole/

### Version

2021.8.8

### Additional information

Logs when `entity_id ` is not set:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 525, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1219, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 215, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 339, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/helpers/config_validation.py", line 134, in validate
    raise vol.Invalid("must contain at least one of {}.".format(", ".join(keys)))
TypeError: sequence item 0: expected str instance, Optional found
```

**Comment by frenck** [comment]
it is correct, entity_id is optional, as other targets can be provided instead, for example, an area or a device.

**Comment by bnordli** [comment]
I see, so this is a much more general problem:

`make_entity_service_schema` in `helpers/config_validation.py` calls `has_at_least_one_key(*ENTITY_SERVICE_FIELDS)`, but that dict has `vol.Optional(..)` keys which cannot be sent to `", ".join(keys)`.

So when anyone calls any entity service without providing either `entity_id`, `devide_id` or `area_id` the validation will blow up instead of providing a helpful error.

What is the proper way of escalating this?

**Comment by bnordli** [comment]
I'll just fix it myself :)
