### ISSUE TITLE
Supported in 2021.9.7?

### ISSUE THREAD

**Issue by 0xJoeMartin** [home-assistant/home-assistant.github.io#19437]
### Feedback

Updated HA Core to 2021.9.7 today and now I am getting errors for the Rachio integration.
```
2021-09-22 13:13:32 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry martinjl@gmail.com for rachio
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/usr/src/homeassistant/homeassistant/components/rachio/__init__.py", line 60, in async_setup_entry
webhook_id, webhook_url = await async_get_or_create_registered_webhook_id_and_url(
File "/usr/src/homeassistant/homeassistant/components/rachio/webhooks.py", line 129, in async_get_or_create_registered_webhook_id_and_url
webhook_url = hass.components.webhook.async_generate_url(webhook_id)
File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 70, in async_generate_url
get_url(hass, prefer_external=True, allow_cloud=False),
File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 83, in get_url
request_host = _get_request_host()
File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 123, in _get_request_host
raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
```

### URL

https://www.home-assistant.io/integrations/rachio/

### Version

2021.9.7

**Comment by klaasnicolaas** [comment]
Hi there @0xJoeMartin 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
