### ISSUE TITLE
Tado related errors possibly causing a restart

### ISSUE THREAD

**Issue by jacoscar** [home-assistant/home-assistant.github.io#19543]
### Feedback

I am experiencing random restarts of my HA (Raspberry PI4) Core 2021.8.2,, OS 6.2

I also find these tado related error in the log, could it be related to that?

`File "/usr/src/homeassistant/homeassistant/components/tado/__init__.py", line 159, in update
    self.update_sensor("device", device["shortSerialNo"])
  File "/usr/src/homeassistant/homeassistant/components/tado/__init__.py", line 176, in update_sensor
    in data["characteristics"]["capabilities"]
KeyError: 'characteristics'
2021-09-23 12:23:55 WARNING (MainThread) [homeassistant.components.mqtt.mixins] JSON result was not a dictionary
2021-09-23 12:23:55 WARNING (MainThread) [homeassistant.components.mqtt.mixins] JSON result was not a dictionary
2021-09-23 12:24:41 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/tado/__init__.py", line 74, in <lambda>
    lambda now: tadoconnector.update(),
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 277, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/tado/__init__.py", line 159, in update
    self.update_sensor("device", device["shortSerialNo"])
  File "/usr/src/homeassistant/homeassistant/components/tado/__init__.py", line 176, in update_sensor
    in data["characteristics"]["capabilities"]
KeyError: 'characteristics'
2021-09-23 12:29:41 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/tado/__init__.py", line 74, in <lambda>
    lambda now: tadoconnector.update(),
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 277, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/tado/__init__.py", line 159, in update
    self.update_sensor("device", device["shortSerialNo"])
  File "/usr/src/homeassistant/homeassistant/components/tado/__init__.py", line 176, in update_sensor
    in data["characteristics"]["capabilities"]
KeyError: 'characteristics'
2021-09-23 12:34:41 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/tado/__init__.py", line 74, in <lambda>
    lambda now: tadoconnector.update(),
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 277, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/tado/__init__.py", line 159, in update
    self.update_sensor("device", device["shortSerialNo"])
  File "/usr/src/homeassistant/homeassistant/components/tado/__init__.py", line 176, in update_sensor
    in data["characteristics"]["capabilities"]
KeyError: 'characteristics'
2021-09-23 12:39:41 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/tado/__init__.py", line 74, in <lambda>
    lambda now: tadoconnector.update(),
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 277, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/tado/__init__.py", line 159, in update
    self.update_sensor("device", device["shortSerialNo"])
  File "/usr/src/homeassistant/homeassistant/components/tado/__init__.py", line 176, in update_sensor
    in data["characteristics"]["capabilities"]
KeyError: 'characteristics'
2021-09-23 12:44:41 ERROR (SyncWorker_2) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/tado/__init__.py", line 74, in <lambda>
    lambda now: tadoconnector.update(),
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 277, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/tado/__init__.py", line 159, in update
    self.update_sensor("device", device["shortSerialNo"])
  File "/usr/src/homeassistant/homeassistant/components/tado/__init__.py", line 176, in update_sensor
    in data["characteristics"]["capabilities"]
KeyError: 'characteristics'
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.`

### URL

https://www.home-assistant.io/integrations/tado/

### Version

2021.9.7

**Comment by frenck** [comment]
Hi there @jacoscar 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
