### ISSUE TITLE
Unexpected error since last update

### ISSUE THREAD

**Issue by fsfikke** [home-assistant/home-assistant.github.io#20386]
### Feedback

Hi, since a couple of days this integration unfortunately no longer works with the following error:

 ```
2021-11-20 12:22:22 ERROR (MainThread) [homeassistant.components.sma.config_flow] Unexpected exception
  Traceback (most recent call last):
    File "/usr/src/homeassistant/homeassistant/components/sma/config_flow.py", line 76, in async_step_user
      device_info = await validate_input(self.hass, user_input)
    File "/usr/src/homeassistant/homeassistant/components/sma/config_flow.py", line 39, in validate_input
      await sma.new_session()
    File "/usr/local/lib/python3.9/site-packages/pysma/__init__.py", line 247, in new_session
      body = await self._post_json(URL_LOGIN, self._new_session_data)
    File "/usr/local/lib/python3.9/site-packages/pysma/__init__.py", line 177, in _post_json
      return await self._request_json(hdrs.METH_POST, url, **params)
    File "/usr/local/lib/python3.9/site-packages/pysma/__init__.py", line 118, in _request_json
      async with self._aio_session.request(
    File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
      self._resp = await self._coro
    File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 619, in _request
      break
    File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 656, in __exit__
      raise asyncio.TimeoutError from None
  asyncio.exceptions.TimeoutError
```

I have removed the integration and tried to add it again without success:
![Untitled](https://user-images.githubusercontent.com/6105891/142761093-8e158c04-829d-4351-afa1-07672f333385.jpg)

No combination of checkboxes works. I have rebooted the SMA inverter, assigned it a different IP and changed the password without prevail.

Pysma is able to connect to the inverter so I'm sure the details I provided are correct:
![pysmaex copy](https://user-images.githubusercontent.com/6105891/142761270-f00fd164-ea71-4564-954b-83d1b5b36b5f.jpg)

I would love to find a solution to this as the integration was working just fine before.

### URL

https://www.home-assistant.io/integrations/sma/

### Version

2021.11.5

**Comment by rklomp** [comment]
What was the last version this was working for you?

**Comment by fsfikke** [comment]
The 15th of November was the last entry in my Energy dashboard from the inverter.

**Comment by rklomp** [comment]
No changes to the SMA integration where made in the latest releases.

The `TimeoutError` points to issues with the connection between HA en the Home Assistant device. The screenshot of your logging is not from HA to the SMA, but from your laptop to the SMA.



Ps. You created an issue in the wrong repository. This one is for documentation only.

**Comment by frenck** [comment]
Hi there @fsfikke 👋 

It seems like you want to report an issue with an Home Assistant Core integration, however, you have submitted documentation feedback instead. If you want to report an issue with an integration, please raise one here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
