### ISSUE TITLE
mqtt.select: List of options that can be selected requires 2 option minimum

### ISSUE THREAD

**Issue by helgeerbe** [home-assistant/home-assistant.github.io#20411]
### Feedback

options list REQUIRED
List of options that can be selected.

Should be
options list REQUIRED
List of options (minimum 2) that can be selected.

### URL

https://www.home-assistant.io/integrations/select.mqtt/

### Version

2021.11.5

### Additional information

Providing just a single option results in an Error:

````log
2021-11-21 11:49:10 INFO (MainThread) [homeassistant.components.mqtt.discovery] Found new component: select picframe_directory
2021-11-21 11:49:10 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_select_mqtt': ({'name': 'picframe_directory', 'icon': 'mdi:folder-multiple-image', 'options': ['Pictures'], 'state_topic': 'homeassistant/sensor/picframe/state', 'command_topic': 'picframe/directory', 'value_template': '{{ value_json.directory}}', 'availability_topic': 'homeassistant/switch/picframe/available', 'unique_id': 'picframe_directory', 'device': {'identifiers': ['picframe']}, 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/select.py", line 39, in validate_config
    raise vol.Invalid(f"'{CONF_OPTIONS}' must include at least 2 options")
voluptuous.error.Invalid: 'options' must include at least 2 options
````

I personally think, input_select should support also a single option. My device [picframe] (https://github.com/helgeerbe/picframe) makes use of input_select to provide the selection of one image folder out of 1 to many folders.

As a workaroud I have to provide an empty dummy folder to get it working (https://github.com/helgeerbe/picframe/issues/196).

**Comment by emontnemery** [comment]
I'm not sure if it should be 1..many or 2..many 🤷 
Why does your picture frame expose a select if only one option is possible?

**Comment by helgeerbe** [comment]
From my point of view it should be 1..many.  

There is always the root folder. But at any time you could add additional image directories (e. g. portraits, animals).  If you select the root folder, all images are displayed. If you select a subfolder only the images (e. g. animals) in the subfolder are displayed.

I know that a single option is not really an option. It's more a label. But in home assistant I can't change dynamically ui elements with different entity-ids.

But via mqtt I can add or delete option elements dynamically in input_select.

**Comment by helgeerbe** [comment]
This is the sample dashboard for picframe in home assistant. Mostly all entities are created via mqtt discovery.

![Übersicht_-_Home_Assistant](https://user-images.githubusercontent.com/59169507/143039164-9c10769c-eeab-45a8-80d2-7adfa6bc581a.png)

**Comment by emontnemery** [comment]
Thanks for explaining, agreed it makes sense to remove the restrictions, done in home-assistant/core#60281
