### ISSUE TITLE
vague/missing Switch Bot integration steps

### ISSUE THREAD

**Issue by jblaneharris** [home-assistant/home-assistant.github.io#20462]
### Feedback

When attempting to integrate my Switch Bot curtain devices, the integration prompts for a "name" which is required, and a password - neither of which are mentioned in the steps. The only thing we're told to obtain from Switch Bot is the MAC that auto-populates, so that seems more of a validation step than something requiring any input.

I'm not aware of a password that might be needed to connect this device locally through bluetooth, are there any missing pieces?

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2021.11.5

**Comment by meluvalli** [comment]
I second this and also the SwitchBot integration just doesn't work for me at.   It sees it queries the device and gets the status, but can't control it.  If I have the curtains closed through app, it shows the curtains are closed.  If I have the curtains open through app, it shows they are open.   So I know it can talk to it, but then I can never send a command to open/close.

Everything I see on this plugin is so old and out dated, I don't know how anyone could be using this thing!

Oh, and here is the logs when I try to open/close incase anyone cares!

<pre>
2021-12-28 08:25:58 WARNING (SyncWorker_5) [switchbot] Cannot connect to Switchbot. Retrying (remaining: 3)
2021-12-28 08:26:02 WARNING (SyncWorker_5) [switchbot] Cannot connect to Switchbot. Retrying (remaining: 2)
2021-12-28 08:26:05 WARNING (SyncWorker_5) [switchbot] Cannot connect to Switchbot. Retrying (remaining: 1)
2021-12-28 08:26:07 ERROR (SyncWorker_5) [switchbot] Switchbot communication failed. Stopping trying
NoneType: None
2021-12-28 08:26:07 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall cover.open_cover (c:a3af66bd3cfe158ada841ce3c9b6f2b5): entity_id=['cover.meluvalli_hotmail_com']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1511, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/switchbot/cover.py", line 101, in async_open_cover
    await self.hass.async_add_executor_job(self._device.open)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/switchbot/__init__.py", line 624, in open
    if result[0] == 1:
IndexError: index out of range
</pre>

**Comment by chaseoes** [comment]
👍
