### ISSUE TITLE
VeSync Integration not showin Air Purifiers

### ISSUE THREAD

**Issue by derhally** [home-assistant/home-assistant.github.io#20479]
### Feedback

I have the Levoit 300s and 400s air purfiers and they are not showing up as part of the VeSync integration.

I noticed the following in the Core logs when trying to reload/reinstall the integration

```
2021-11-28 09:51:10 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry derhally@gmail.com for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 85, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-11-28 09:51:10 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry derhally@gmail.com for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 220, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-11-28 09:51:10 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry derhally@gmail.com for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 546, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

### URL

https://www.home-assistant.io/integrations/vesync/

### Version

2021.11.5

**Comment by Crisby23** [comment]
I have the same issue with 300S purifier. I can install the integretation, enter e-mail and password but i dont see any devices in home assistant. Maybe its because the 300S is not in the list of supported devices, only the 200S purifier. 

Log shows:
```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:177
First occurred: 20:17:54 (2 occurrences)
Last logged: 20:17:54

Error unloading entry xxx@yyyy.de for switch
Error unloading entry xxx@yyyy.de for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 452, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 95, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 177, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

**Comment by derhally** [comment]
400s works now, but 300S shows the following errors

```
2022-01-04 15:07:50 WARNING (MainThread) [homeassistant.components.vesync.fan] Bedroom1 - Unknown device type - Core300S
2022-01-04 15:07:51 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.
```
