### ISSUE TITLE
Issue with components/buienradar when it is raining

### ISSUE THREAD

**Issue by samimasad** [home-assistant/home-assistant.github.io#20530]
### Feedback

the integration fail when there is rain since few days ago , seems issue with parsing "," vs "."
Logger: homeassistant
Source: components/buienradar/util.py:147
First occurred: 6:17:03 AM (2 occurrences)
Last logged: 6:17:03 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/buienradar/util.py", line 147, in async_update
    result = parse_data(
  File "/usr/local/lib/python3.9/site-packages/buienradar/buienradar.py", line 37, in parse_data
    return parse_json_data(content, raincontent,
  File "/usr/local/lib/python3.9/site-packages/buienradar/buienradar_json.py", line 306, in parse_json_data
    data = __parse_precipfc_data(raincontent, timeframe)
  File "/usr/local/lib/python3.9/site-packages/buienradar/buienradar_json.py", line 574, in __parse_precipfc_data
    mmu = 10**(float((int(val) - 109)) / 32)
ValueError: invalid literal for int() with base 10: '92,2678801510292'

### URL

https://www.home-assistant.io/integrations/buienradar/

### Version

2021.11.5

**Comment by RobBie1221** [comment]
This is the wrong repo for core issues. Also this has been solved already, wait for a new release...

**Comment by frenck** [comment]
Hi there @samimasad 👋 

RobBbie1221 is right! It seems like you wanted to report an issue, however, you have submitted documentation feedback instead. Nevertheless, the issue has been addressed and will be in the next Home Assistant release.

../Frenck
