### ISSUE TITLE
Error atome sensor

### ISSUE THREAD

**Issue by Xavier80** [home-assistant/home-assistant.github.io#20724]
### Feedback

Atome linky sensors do not update anymore sometimes even after rebooting the system.
Shown measurements are stopped after about 4 hours.
Please see below details of the error.

### URL

https://www.home-assistant.io/integrations/atome/

### Version

2021.12.2

### Additional information

Logger: homeassistant.helpers.entity
Source: components/atome/sensor.py:145
First occurred: 12:40:59 (102 occurrences)
Last logged: 12:57:30

Update for sensor.atome_daily fails
Update for sensor.atome_weekly fails
Update for sensor.atome_monthly fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/atome/sensor.py", line 267, in update
    update_function()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 195, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/atome/sensor.py", line 188, in update_day_usage
    ) = self._retrieve_period_usage_with_retry(DAILY_TYPE)
  File "/usr/src/homeassistant/homeassistant/components/atome/sensor.py", line 161, in _retrieve_period_usage_with_retry
    ) = self._retrieve_period_usage(period_type)
  File "/usr/src/homeassistant/homeassistant/components/atome/sensor.py", line 145, in _retrieve_period_usage
    values = self.atome_client.get_consumption(period_type)
  File "/usr/local/lib/python3.9/site-packages/pyatome/client.py", line 190, in get_consumption
    return self._get_consumption(period)
  File "/usr/local/lib/python3.9/site-packages/pyatome/client.py", line 177, in _get_consumption
    json_output = req.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Xavier80** [comment]
Is there any way to raise the issue ?

**Comment by klaasnicolaas** [comment]
Hi there @Xavier80 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
