### ISSUE TITLE
Yale login auth failing

### ISSUE THREAD

**Issue by tindall21047** [home-assistant/home-assistant.github.io#20844]
### Feedback

Bought a Yale Door lock, made an account (just in order to use the home-assistant app, I'd prefer if I could do this without cloud tie ins), installed yale access app on my phone, confirmed able to lock and unlock front door.

Tried installing 'august' integration (having read this was the correct integration for my lock) and got a 'success' message when attempting to log in with email (phone number didn't work). No devices or entites showing up for the integration.

I took a look at the home assitant logs and I see:

2021-12-23 11:18:50 ERROR (SyncWorker_0) [yalesmartalarmclient.auth] Authentication incorrect
2021-12-23 11:18:50 ERROR (MainThread) [homeassistant.components.yale_smart_alarm.const] Authentication failed. Check credentials

as well as several of these:

2021-12-23 11:18:04 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pubnub/pubnub_asyncio.py", line 531, in _send_leave_helper
    self._listener_manager.announce_status(envelope.status)
  File "/usr/local/lib/python3.9/site-packages/pubnub/managers.py", line 194, in announce_status
    callback.status(self._pubnub, status)
  File "/usr/local/lib/python3.9/site-packages/yalexs/pubnub_async.py", line 29, in status
    status.category,
AttributeError: 'NoneType' object has no attribute 'category'

I know that the authentication credentials are working because I just used them in the yale access app (and tried uninstalling app and reinstalling, retrying with same credentials).

Now, when I logged in via yale access it did prompt me with a one time password to my email address, so perhaps this login now requires one time passwords and the integration needs updating?

In any case, I throw myself upon whatever admin gods may be listening. What are my next steps?j

Cheers,
Christopher

### URL

https://www.home-assistant.io/integrations/august/

### Version

2021.12.5

**Comment by bdraco** [comment]
```
2021-12-23 11:18:50 ERROR (SyncWorker_0) [yalesmartalarmclient.auth] Authentication incorrect
2021-12-23 11:18:50 ERROR (MainThread) [homeassistant.components.yale_smart_alarm.const] Authentication failed. Check credentials
```

This is from another integration and not related

**Comment by frenck** [comment]
Hi there @tindall21047 👋 

It seems like you want to report an issue with an Home Assistant integrations, however, you have submitted documentation feedback instead. Please file issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
