### ISSUE TITLE
Smart Tub integration with a D1 Triad 36 Hot Tub

### ISSUE THREAD

**Issue by gdeuss** [home-assistant/home-assistant.github.io#20896]
### Feedback

see in additional info. In general, it appears that may not be a documentation issue, rather the integration si not working as intended for the specific tub but I do not know how to get support for that if support is even available.

### URL

https://www.home-assistant.io/integrations/smarttub/

### Version

2021.12.6

### Additional information

The integration provides the correct tub, in my case "Triad™ 36 by D1" but none of the services listed in this documentation were available. All points register as "Unavailable".
Since it is returning some correct info, actually just the correct tub model, I have to assume login into the Web Account is not the issue.
The following screenshot is what I get after HA links it

![image](https://user-images.githubusercontent.com/95149025/147513821-51e03c3b-68c3-4d30-8220-f1f887fa502f.png)

The hot tub has two jets, and two LED light circuits and the thermostat that can all be operated via the smart tub app. At least some of the integrations shown in the screenshot are not available on the Smart Tub App.

**Comment by gdeuss** [comment]
Forgot to show the "Controls" part of the integration, see below
![image](https://user-images.githubusercontent.com/95149025/147606200-1d5e529a-ef3f-48c6-b497-1258041058d2.png)

**Comment by gdeuss** [comment]
These are the current error logs:



**Error while setting up smarttub platform for binary_sensor**

Logger: homeassistant.components.binary_sensor
Source: components/smarttub/binary_sensor.py:52
Integration: Binary sensor (documentation, issues)
First occurred: 10:51:14 AM (1 occurrences)
Last logged: 10:51:14 AM

Error while setting up smarttub platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/smarttub/binary_sensor.py", line 52, in async_setup_entry
    for reminder in controller.coordinator.data[spa.id][ATTR_REMINDERS].values()
TypeError: 'NoneType' object is not subscriptable



**`Error while setting up smarttub platform for light`**
Logger: homeassistant.components.light
Source: components/smarttub/light.py:32
Integration: Light (documentation, issues)
First occurred: 10:51:14 AM (1 occurrences)
Last logged: 10:51:14 AM

Error while setting up smarttub platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/smarttub/light.py", line 29, in async_setup_entry
    entities = [
  File "/usr/src/homeassistant/homeassistant/components/smarttub/light.py", line 32, in <listcomp>
    for light in controller.coordinator.data[spa.id][ATTR_LIGHTS].values()
TypeError: 'NoneType' object is not subscriptable

**Error while setting up smarttub platform for switch*
Logger: homeassistant.components.switch
Source: components/smarttub/switch.py:20
Integration: Switch (documentation, issues)
First occurred: 10:51:14 AM (1 occurrences)
Last logged: 10:51:14 AM

Error while setting up smarttub platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/smarttub/switch.py", line 17, in async_setup_entry
    entities = [
  File "/usr/src/homeassistant/homeassistant/components/smarttub/switch.py", line 20, in <listcomp>
    for pump in controller.coordinator.data[spa.id][ATTR_PUMPS].values()
TypeError: 'NoneType' object is not subscriptable

**Unexpected error fetching smarttub data: object of type 'NoneType' has no len()*
Logger: homeassistant.components.smarttub.controller
Source: components/smarttub/controller.py:98
Integration: SmartTub (documentation, issues)
First occurred: 10:51:14 AM (123 occurrences)
Last logged: 12:56:35 PM

Unexpected error fetching smarttub data: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/usr/src/homeassistant/homeassistant/components/smarttub/controller.py", line 90, in async_update_data
    data[spa.id] = await self._get_spa_data(spa)
  File "/usr/src/homeassistant/homeassistant/components/smarttub/controller.py", line 98, in _get_spa_data
    full_status, reminders, errors = await asyncio.gather(
  File "/usr/local/lib/python3.9/site-packages/smarttub/api.py", line 206, in get_reminders
    return [
  File "/usr/local/lib/python3.9/site-packages/smarttub/api.py", line 207, in <listcomp>
    SpaReminder(self, **reminder_info)
  File "/usr/local/lib/python3.9/site-packages/smarttub/api.py", line 469, in __init__
    self.last_updated = dateutil.parser.isoparse(properties["lastUpdated"])
  File "/usr/local/lib/python3.9/site-packages/dateutil/parser/isoparser.py", line 37, in func
    return f(self, str_in, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dateutil/parser/isoparser.py", line 134, in isoparse
    components, pos = self._parse_isodate(dt_str)
  File "/usr/local/lib/python3.9/site-packages/dateutil/parser/isoparser.py", line 208, in _parse_isodate
    return self._parse_isodate_common(dt_str)
  File "/usr/local/lib/python3.9/site-packages/dateutil/parser/isoparser.py", line 213, in _parse_isodate_common
    len_str = len(dt_str)
TypeError: object of type 'NoneType' has no len()

**Comment by mdz** [comment]
Thanks for your report and the logs. This looks like a bug in the underlying library, https://github.com/mdz/python-smarttub, so I've opened an issue about this there. Please follow up in https://github.com/mdz/python-smarttub/issues/22

**Comment by gdeuss** [comment]
Thanks Matt, your prompt fix corrected the mapping and it is now connecting to the tub with the appropriate points. There are still some minor issues with it and I will follow up with those in detail once I have time to look into them some more in the New Year. The most important integration, the temperature thermostat, works now great and is reliably providing setpoint and temperature values. Thank you for looking into this and my best wishes to you in the New Year. Btw, I enjoyed reading your personal web blog, I wish your thinking would be more common in this world

**Comment by gdeuss** [comment]
Sorry about not responding earlier, the issue was resolved by the author and it should be closed

Gustav Deuss
GRD Energy, Inc.
1 Avenue of the Palms, Suite 10C
San Francisco, CA 94130
O 415 891 8824
M 650 291 2569
