### ISSUE TITLE
EZVIZ integration: most features (for example alarm_tome switch) do not work

### ISSUE THREAD

**Issue by johanvh83** [home-assistant/home-assistant.github.io#21101]
### Feedback

Have 2 Husky Air with firmware V5.3.0 build 210719
After installation of the integration got 35 entities for each camera.
Most switched do not work.
When I toggle the alarm_tone (off to on) nothing happens and after few seconds switch comes back to off position.

Log shows:
Logger: homeassistant.components.websocket_api.http.connection
Source: components/ezviz/switch.py:69
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 5:08:08 PM (4 occurrences)
Last logged: 5:14:14 PM

[140172420905808] Failed to turn on switch {self._name}
[140172067008912] Failed to turn on switch {self._name}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/ezviz/switch.py", line 64, in async_turn_on
    update_ok = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyezviz/client.py", line 979, in switch_status
    return self._switch_status(serial, status_type, enable)
  File "/usr/local/lib/python3.9/site-packages/pyezviz/client.py", line 395, in _switch_status
    raise PyEzvizError(
pyezviz.exceptions.PyEzvizError: Could not set the switch: Got 200 : {"meta":{"code":2004,"message":"设备异常","moreInfo":{"DEVICE_EXCEPTION":"4"}}})

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/ezviz/switch.py", line 69, in async_turn_on
    raise PyEzvizError("Failed to turn on switch {self._name}") from err
pyezviz.exceptions.PyEzvizError: Failed to turn on switch {self._name}

### URL

https://www.home-assistant.io/integrations/ezviz/

### Version

2021.12.8

**Comment by lainwir3d** [comment]
Same here. Model C3X v5.2.5 build 210511.

**Comment by lainwir3d** [comment]
Doesn't work with v5.2.5 build 210930 either.
