### ISSUE TITLE
SolarEdge integration issue

### ISSUE THREAD

**Issue by robloskamp** [home-assistant/home-assistant.github.io#21434]
### Feedback

When I enter my Site ID and API key an “unknown error occurred” message is displayed.
HAS is running the most recent version (core-2021.12.10) and the side id and api key is working. Tested it via the URL https://monitoringapi.solaredge.com/equipment/<Site Id>/list?api_key=<API Key>

**The core log shows the following errors:**

Logger: aiohttp.server
Source: components/solaredge/config_flow.py:45
First occurred: 12:21:42 (7 occurrences)
Last logged: 12:22:07

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/components/solaredge/config_flow.py", line 69, in async_step_user
    can_connect = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/solaredge/config_flow.py", line 45, in _check_site
    response = api.get_details(site_id)
  File "/usr/local/lib/python3.9/site-packages/solaredge/solaredge.py", line 81, in get_details
    r = requests.get(url, params)
TypeError: get() takes 1 positional argument but 2 were given

### URL

https://www.home-assistant.io/integrations/solaredge/

### Version

2021.12.10

**Comment by frenck** [comment]
Hi there @robloskamp 👋 

It seems like you want to report an issue for an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
