### ISSUE TITLE
Zwave cover: TypeError: an integer is required

### ISSUE THREAD

**Issue by Timple** [home-assistant/home-assistant.github.io#2154]
Good day, I have a fibaro roller shutter v2 device implemented. Works fine with the slider. But the up/down buttons do not work. This is the error I get:
```
17-02-26 20:16:40 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: service_call_id=139878753767944-3, domain=cover, service=open_cover, service_data=entity_id=cover.fibaro_system_fgrm222_roller_shutter_controller_2_level_10_0>
17-02-26 20:16:40 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "uvloop/future.pyx", line 374, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:112704)
  File "/usr/src/app/homeassistant/core.py", line 1001, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/usr/src/app/homeassistant/components/cover/__init__.py", line 161, in async_handle_cover_service
    yield from getattr(cover, method['method'])(**params)
  File "uvloop/future.pyx", line 230, in __iter__ (uvloop/loop.c:110600)
  File "uvloop/future.pyx", line 432, in uvloop.loop.BaseTask._fast_wakeup (uvloop/loop.c:113980)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108900)
  File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/components/cover/zwave.py", line 102, in open_cover
    zwave.NETWORK.manager.pressButton(self._open_id)
  File "src-lib/libopenzwave/libopenzwave.pyx", line 3431, in libopenzwave.PyManager.pressButton (src-lib/libopenzwave/libopenzwave.cpp:25117)
TypeError: an integer is required
```

**Comment by Timple** [comment]
Sorry, wrong repository. Moved: https://github.com/home-assistant/home-assistant/issues/6275
