### ISSUE TITLE
Can't add new mill oven

### ISSUE THREAD

**Issue by irowan** [home-assistant/home-assistant.github.io#21753]
### Feedback

Trying to add my new 3rd gen oven. Typing the correct ip.  Getting this.

Oven is on 2.4GHz network. The official mill app works with the oven.
I have chosen "no cloud and local api." in the config of the oven.

### URL

https://www.home-assistant.io/integrations/mill/

### Version

2022.2.9

### Additional information

<img width="433" alt="Screenshot 2022-02-23 at 02 51 02" src="https://user-images.githubusercontent.com/36939297/155249818-5fd761ae-91d5-4c78-b994-3377d21a34f5.png">

**Comment by irowan** [comment]
Logger: mill_local Source: /usr/local/lib/python3.9/site-packages/mill_local/__init__.py:89 First occurred: 00:10:28 (2 occurrences) Last logged: 02:50:58
Failed to get status
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.100.154', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mill_local/__init__.py", line 83, in get_status
    self._status = await self._request("status")
  File "/usr/local/lib/python3.9/site-packages/mill_local/__init__.py", line 101, in _request
    async with self.websession.get(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.100.154:80 ssl:default [Connect call failed ('192.168.100.154', 80)]

**Comment by frenck** [comment]
Hi there @irowan 👋 

It seems like you want to report a bug with an Home Assistant Core integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here:
<https://github.com/home-assistant/core/issues>


Thanks 👍 

../Frenck
