### ISSUE TITLE
I get the error "Error setting up platform legacy luci" in the logs.

### ISSUE THREAD

**Issue by skepticautonetic** [home-assistant/home-assistant.github.io#21802]
### Feedback

I get the error "Error setting up platform legacy luci" in the logs.

Logger: homeassistant.components.device_tracker
Source: components/luci/device_tracker.py:54 
Integration: Device tracker ([documentation](https://www.home-assistant.io/integrations/device_tracker), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+device_tracker%22)) 
First occurred: 1:48:21 PM (1 occurrences) 
Last logged: 1:48:21 PM

Error setting up platform legacy luci
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 245, in async_setup_legacy
    scanner = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/luci/device_tracker.py", line 43, in get_scanner
    scanner = LuciDeviceScanner(config[DOMAIN])
  File "/usr/src/homeassistant/homeassistant/components/luci/device_tracker.py", line 54, in __init__
    self.router = OpenWrtRpc(
  File "/usr/local/lib/python3.9/site-packages/openwrt_luci_rpc/__init__.py", line 31, in __init__
    self.router = OpenWrtLuciRPC(host_url, username, password,
  File "/usr/local/lib/python3.9/site-packages/openwrt_luci_rpc/openwrt_luci_rpc.py", line 61, in __init__
    self._refresh_token()
  File "/usr/local/lib/python3.9/site-packages/openwrt_luci_rpc/openwrt_luci_rpc.py", line 69, in _refresh_token
    self.token = self._call_json_rpc(auth_url, 'login',
  File "/usr/local/lib/python3.9/site-packages/openwrt_luci_rpc/openwrt_luci_rpc.py", line 251, in _call_json_rpc
    raise PageNotFoundError("404 returned "
openwrt_luci_rpc.exceptions.PageNotFoundError: 404 returned from http://192.168.10.1/cgi-bin/luci/rpc/auth. Ensure you have installed package `luci-mod-rpc`.

No luci-mod-rpc package available in OpenWRT 

### URL

https://www.home-assistant.io/integrations/luci/

### Version

2022.2.9

**Comment by frenck** [comment]
Have you installed `luci-mod-rpc` as per integration documentation and the error message shown?
