### ISSUE TITLE
SABnzb stopped working

### ISSUE THREAD

**Issue by seanscott1977** [home-assistant/home-assistant.github.io#21898]
### Feedback

Stopped working after the last update

### URL

https://www.home-assistant.io/integrations/sabnzbd/

### Version

2022.3.1

### Additional information

Logger: homeassistant.setup
Source: components/sabnzbd/__init__.py:170
First occurred: 3:41:17 PM (1 occurrences)
Last logged: 3:41:17 PM

Error during setup of component sabnzbd
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/src/homeassistant/homeassistant/components/sabnzbd/__init__.py", line 218, in async_setup
    await async_configure_sabnzbd(hass, conf, use_ssl, name, api_key)
  File "/usr/src/homeassistant/homeassistant/components/sabnzbd/__init__.py", line 196, in async_configure_sabnzbd
    if await async_check_sabnzbd(sab_api):
  File "/usr/src/homeassistant/homeassistant/components/sabnzbd/__init__.py", line 170, in async_check_sabnzbd
    await sab_api.check_available()
  File "/usr/local/lib/python3.9/site-packages/pysabnzbd/__init__.py", line 93, in check_available
    await self._call(params)
  File "/usr/local/lib/python3.9/site-packages/pysabnzbd/__init__.py", line 41, in _call
    async with timeout(self._timeout, loop=self._session.loop):
TypeError: timeout() got an unexpected keyword argument 'loop'

**Comment by guitarflipper** [comment]
I got the same error after updating to version 2022.3.1. Note for note.

**Comment by drthanwho** [comment]
This is an issue with the integration. This repository is about issues with the documentation of the website.

**Comment by frenck** [comment]
The integration has been renewed for Home Assistant 2022.5, please update to that version. If the issue remains, please raise an issue in the Core issue tracker.

Thanks! 👍 

../Frenck
