### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by skydivingpt** [home-assistant/home-assistant.github.io#22077]
### Feedback

Logger: aiohttp.server
Source: components/renault/renault_hub.py:107
First occurred: 8:42:06 PM (3 occurrences)
Last logged: 8:46:39 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 166, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/components/renault/config_flow.py", line 44, in async_step_user
    return await self.async_step_kamereon()
  File "/usr/src/homeassistant/homeassistant/components/renault/config_flow.py", line 75, in async_step_kamereon
    accounts = await self.renault_hub.get_account_ids()
  File "/usr/src/homeassistant/homeassistant/components/renault/renault_hub.py", line 107, in get_account_ids
    for account in await self._client.get_api_accounts():
  File "/usr/local/lib/python3.9/site-packages/renault_api/renault_client.py", line 58, in get_api_accounts
    response = await self.get_person()
  File "/usr/local/lib/python3.9/site-packages/renault_api/renault_client.py", line 54, in get_person
    return await self.session.get_person()
  File "/usr/local/lib/python3.9/site-packages/renault_api/renault_session.py", line 175, in get_person
    return await kamereon.get_person(
  File "/usr/local/lib/python3.9/site-packages/renault_api/kamereon/__init__.py", line 171, in get_person
    await request(
  File "/usr/local/lib/python3.9/site-packages/renault_api/kamereon/__init__.py", line 153, in request
    http_response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/persons/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx?country=PT')

### URL

https://www.home-assistant.io/integrations/renault/

### Version

2022.3.5

### Additional information

i've confirm the user and pass throug Renault RLink app,
it seems the authentication in HA is somehow falling in error  (token ?!)

Tanks

**Comment by skydivingpt** [comment]
maybe this help more

Logger: homeassistant.config_entries
Source: components/renault/renault_hub.py:59
First occurred: 8:37:11 PM (1 occurrences)
Last logged: 8:37:11 PM

Error setting up entry RZoe for renault
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/renault/__init__.py", line 28, in async_setup_entry
    await renault_hub.async_initialise(config_entry)
  File "/usr/src/homeassistant/homeassistant/components/renault/renault_hub.py", line 59, in async_initialise
    vehicles = await self._account.get_vehicles()
  File "/usr/local/lib/python3.9/site-packages/renault_api/renault_account.py", line 62, in get_vehicles
    return await self.session.get_account_vehicles(
  File "/usr/local/lib/python3.9/site-packages/renault_api/renault_session.py", line 188, in get_account_vehicles
    return await kamereon.get_account_vehicles(
  File "/usr/local/lib/python3.9/site-packages/renault_api/kamereon/__init__.py", line 232, in get_account_vehicles
    await request(
  File "/usr/local/lib/python3.9/site-packages/renault_api/kamereon/__init__.py", line 153, in request
    http_response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError**: 403, message='Forbidden', url=URL('https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/xxxxxxxxxxxxxxxxxxxxxx/vehicles?country=PT')**

**Comment by klaasnicolaas** [comment]
Hi there @skydivingpt 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
