### ISSUE TITLE
"Unknown error" on adding integration.

### ISSUE THREAD

**Issue by spleijers** [home-assistant/home-assistant.github.io#22263]
### Feedback

"Unknown error occurred" on adding integration. Seems to miss something: datum_eerste_afgifte_nederland?

![image](https://user-images.githubusercontent.com/26082688/161960099-45e20e98-38f3-4c4f-88a1-d331e4928389.png)

### URL

https://www.home-assistant.io/integrations/rdw/

### Version

2022.3.8

### Additional information

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 166, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/components/rdw/config_flow.py", line 31, in async_step_user
    vehicle = await rdw.vehicle(
  File "/usr/local/lib/python3.9/site-packages/vehicle/rdw.py", line 135, in vehicle
    return Vehicle.parse_obj(data[0])  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/pydantic/main.py", line 511, in parse_obj
    return cls(**obj)
  File "/usr/local/lib/python3.9/site-packages/pydantic/main.py", line 331, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Vehicle
datum_eerste_afgifte_nederland
  field required (type=value_error.missing)

**Comment by frenck** [comment]
Please update to Home Assistant Core 2022.4, it fixed the issue 👍 

../Frenck
