### ISSUE TITLE
April updates for unifi network integration

### ISSUE THREAD

**Issue by kennyme** [home-assistant/home-assistant.github.io#22332]
April updates for unifi network integration
Logger: aiohttp.server
Source: components/unifi/config_flow.py:259 
First occurred: 4:51:42 AM (1 occurrences) 
Last logged: 4:51:42 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)

**Comment by kennyme** [comment]
points to my unify network

**Comment by kennyme** [comment]
unifi network , for some reason displayed managed by another
