### ISSUE TITLE
Whirlpool Integration username and password prompt 

### ISSUE THREAD

**Issue by mltiede** [home-assistant/home-assistant.github.io#22795]
### Feedback

I got a microwave with 6th sense so thought I would try the integration even though it probably isn't supported.  I was presented with a login dialog, but it doesn't say what user and password it wants.  Is it the HA one?  didn't work.  Is it the one used with the whirlpool app?  didn't work.  Something else?  Would be helpful if the dialog said what it was asking for.

Consequently, I couldn't even install the integration.

### URL

https://www.home-assistant.io/integrations/whirlpool/

### Version

2022.5.4

**Comment by abmantis** [comment]
Whirlpool seems to have changed their API for some users. This is probably a consequence/duplicate of https://github.com/home-assistant/core/issues/69602

**Comment by nandorsoma** [comment]
Hey!
I'm also experiencing an issue during login. Getting unexpected error on the UI with a bit different stack trace than the linked ones in the mentioned duplicate:
```
2022-06-20 20:34:28 ERROR (MainThread) [homeassistant.components.whirlpool.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/whirlpool/config_flow.py", line 57, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/usr/src/homeassistant/homeassistant/components/whirlpool/config_flow.py", line 32, in validate_input
    await auth.do_auth()
  File "/usr/local/lib/python3.9/site-packages/whirlpool/auth.py", line 104, in do_auth
    "access_token": fetched_auth_data.get("access_token", ""),
AttributeError: 'NoneType' object has no attribute 'get'
2022-06-20 20:35:30 ERROR (MainThread) [homeassistant.components.whirlpool.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/whirlpool/config_flow.py", line 57, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/usr/src/homeassistant/homeassistant/components/whirlpool/config_flow.py", line 32, in validate_input
    await auth.do_auth()
  File "/usr/local/lib/python3.9/site-packages/whirlpool/auth.py", line 104, in do_auth
    "access_token": fetched_auth_data.get("access_token", ""),
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by abmantis** [comment]
@mltiede  is this still happening? I think auth is working again.
