### ISSUE TITLE
Cannot add extra accounts to Steam integration

### ISSUE THREAD

**Issue by Mithrox** [home-assistant/home-assistant.github.io#22821]
### Feedback

Hi.

After upgrade to 2022.5.x (I went from 4.7 to 5.5) none of my Steam accounts except my own show status. I have removed Steam integration fully and removed everything from the yaml files, and then restarted and re-added it. Still only my own account shows up. All the accounts I had registered was friends accounts with open profile.

![image](https://user-images.githubusercontent.com/58890682/169536671-ae5fae1c-ab47-43fa-b99f-7af11dd7fadb.png)

I get this error when pressing Configure in the Steam addon, so I am not sure where I can add other accounts now.

Please advise on what can be the issue.

### URL

https://www.home-assistant.io/integrations/steam_online/

### Version

2022.5.5

**Comment by tkdrob** [comment]
At what point does the screenshot pop up for you?

**Comment by tkdrob** [comment]
Try a different browser first. This can happen with the aggressive caching that is being done.

**Comment by tkdrob** [comment]
Is there any stack trace in the logs?

**Comment by Mithrox** [comment]
> Is there any stack trace in the logs?

There may be, if you would educate me on how to gather then and I will for sure add it here :)

**Comment by Mithrox** [comment]
> Is there any stack trace in the logs?

`Logger: aiohttp.server
Source: components/steam_online/config_flow.py:192
First occurred: 23:16:15 (1 occurrences)
Last logged: 23:16:15

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/steam/api.py", line 152, in download
    req = urlopen(urlrequest(self._url, headers=head),
  File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 94, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 243, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 70, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 232, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/components/steam_online/config_flow.py", line 172, in async_step_init
    for name in await self.hass.async_add_executor_job(self.get_accounts)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/steam_online/config_flow.py", line 192, in get_accounts
    _users_str = [user["steamid"] for user in friends["friendslist"]["friends"]]
  File "/usr/local/lib/python3.9/site-packages/steam/api.py", line 220, in __getitem__
    return self.__handle_accessor("__getitem__", *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/steam/api.py", line 200, in __handle_accessor
    self.call()
  File "/usr/local/lib/python3.9/site-packages/steam/api.py", line 242, in call
    data = self._downloader.download()
  File "/usr/local/lib/python3.9/site-packages/steam/api.py", line 171, in download
    raise HTTPError("Server connection failed: {0} ({1})".format(reason, code))
steam.api.HTTPError: Server connection failed: Unauthorized (401)`

**Comment by Mithrox** [comment]
> Try a different browser first. This can happen with the aggressive caching that is being done.

Sorry, I mixed these two together. I did try another browser, but posted the reply on the other case.

**Comment by tkdrob** [comment]
If you set up the integration with only your steam id, can you access the options menu? Then try adding a few people at a time. Let's see if a particular user triggers the 401.

**Comment by Mithrox** [comment]
> If you set up the integration with only your steam id, can you access the options menu? Then try adding a few people at a time. Let's see if a particular user triggers the 401.

I deleted the Steam integration and removed all Steam setup in Yaml, restarted HA completely (boot host), and then added Steam integration with no config other than my API and my ID. I cannot get into configuration so I cannot add any other users. The question is if the "old" users from sensor.yaml was imported into another file somewhere, if so I can delete everything from there as well, but I wouldn't know where that is. Do you know if there is the imported config anywhere?

**Comment by tkdrob** [comment]
That depends on how you havbe your yaml config set up. If you have `sensor:` in `configuration.yaml` then that should be the only place. Some people like me have in a separate file by doing `sensor: !include sensor.yaml`. There is a hidden `.storage` folder inside config that has the `config_entries` file but there should be no steam reference if it is not set up. If your yaml is clean of steam_online, you will not get the warning log that it is deprecated.

**Comment by Mithrox** [comment]
I do not get a warning for deprecated no, it should be clean.

I had my steam setup in sensor.yaml with include from configuration.yaml, correct. And I removed the whole section from it after I removed Steam integration, and then added it again after reboot. But was thinking the upgrade to 2022.5.5 had imported my current yaml steam sensor setup to some other configuration I did not know about.

**Comment by Mithrox** [comment]
Under core.config_entries I only have this, and I suspect its from the new setup as this is the info I did put in when I installed the integration again after deleting it.

            {
                "entry_id": "ef602c148158c81abdd32e954186e9be",
                "version": 1,
                "domain": "steam_online",
                "title": "aTOMic",
                "data": {
                    "api_key": "<my API key>",
                    "account": "76561197961867740"
                },
                "options": {
                    "accounts": {
                        "76561197961867740": "aTOMic"
                    }
                },
                "pref_disable_new_entities": false,
                "pref_disable_polling": false,
                "source": "user",
                "unique_id": "76561197961867740",
                "disabled_by": null

**Comment by tkdrob** [comment]
@Mithrox Lets see if the two fixes solve the problem. If you still see issues after the next patch release/beta, open a new issue. Thanks

**Comment by Mithrox** [comment]
> @Mithrox Lets see if the two fixes solve the problem. If you still see issues after the next patch release/beta, open a new issue. Thanks

I will keep an eye out for the update, assume this will be in the next HA core update?
The other issue now is the constant unknown/unavailable states that come over and over again, do you see that in your History for the different Steam accounts?
