### ISSUE TITLE
local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by fedepupo** [home-assistant/home-assistant.github.io#22931]
### Feedback

Impossible add a new account, i have this error in log file

Error handling request
17:50:10 – (ERRORE) components/bmw_connected_drive/config_flow.py
local variable 'response' referenced before assignment
17:50:10 – (ERRORE) /usr/local/lib/python3.9/site-packages/bimmer_connected/account.py

### URL

https://www.home-assistant.io/integrations/bmw_connected_drive/

### Version

2022.5.5

**Comment by rikroe** [comment]
Thats a temporary issue that is fixed in 2022.6 (to be released tomorrow). For more information please see #72685.

**Comment by frenck** [comment]
Closing this feedback, as it is an issue report (not documentation feedback), that above all has been fixed (release is today 🎉 )

../Frenck

**Comment by fedepupo** [comment]
@gerard33, @rikroe, i've updated to release 2022.6 but now i've this error

`Logger: aiohttp.server
Source: components/bmw_connected_drive/config_flow.py:42
First occurred: 22:27:51 (1 occurrences)
Last logged: 22:27:51

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 205, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/config_flow.py", line 68, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/usr/src/homeassistant/homeassistant/components/bmw_connected_drive/config_flow.py", line 42, in validate_input
    await account.get_vehicles()
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 86, in get_vehicles
    self.vehicles.append(MyBMWVehicle(self, vehicle_dict))
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle/vehicle.py", line 90, in __init__
    self.update_state(vehicle_data)
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle/vehicle.py", line 106, in update_state
    setattr(self, vehicle_attribute, cls.from_vehicle_data(vehicle_data))
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/models.py", line 29, in from_vehicle_data
    parsed = cls._parse_vehicle_data(vehicle_data) or {}
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle/charging_profile.py", line 117, in _parse_vehicle_data
    retval["is_pre_entry_climatization_enabled"] = bool(charging_profile["climatisationOn"])
KeyError: 'climatisationOn'
`

**Comment by rikroe** [comment]
Please create a new issue either in https://github.com/home-assistant/core or the library https://github.com/bimmerconnected/bimmer_connected and we'll keep track from there.

Seems BMW likes to play around with their API much more than before...
