### ISSUE TITLE
What is the device_id?

### ISSUE THREAD

**Issue by maugsburger** [home-assistant/home-assistant.github.io#23232]
### Feedback

I didn't find any clue what to use as device_id.

At first I thought it is the VIN, so I copied it over from https://myr.renault.de/, but it does not work:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/renault/services.py:135
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 09:55:59 (2 occurrences)
Last logged: 10:05:37
[139953752451344] Error handling message: Unknown error (unknown_error)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 636, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/renault/services.py", line 99, in charge_set_schedules
    proxy = get_vehicle_proxy(service_call.data)
  File "/usr/src/homeassistant/homeassistant/components/renault/services.py", line 135, in get_vehicle_proxy
    raise ValueError(f"Unable to find device with id: {device_id}")
ValueError: Unable to find device with id: VF1AGVXXXXXXXXXX
```

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: components/renault/services.py:135
First occurred: 09:55:59 (2 occurrences)
Last logged: 10:05:37
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Unable to find device with id: VF1AGVYF058329942

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/renault/services.py", line 99, in charge_set_schedules
    proxy = get_vehicle_proxy(service_call.data)
  File "/usr/src/homeassistant/homeassistant/components/renault/services.py", line 135, in get_vehicle_proxy
    raise ValueError(f"Unable to find device with id: {device_id}")
ValueError: Unable to find device with id: VF1AGVXXXXXXXXXX
```

So appereantly its not the VIN, but what is it then? Please extend the document about what to use here as argument.

Thanks!

### URL

https://www.home-assistant.io/integrations/renault/

### Version

2022.6.7

**Comment by epenet** [comment]
It is the internal device_id from Home Assistant.
You should have a drop-down available in the Home Assistant UI

**Comment by maugsburger** [comment]
Ah, okay, using the service dev tool this works fine. Starting in scripts.yaml, this was not intuitive.

**Comment by epenet** [comment]
Feel free to provide a PR to adjust the documentation.

**Comment by frenck** [comment]
Device IDs are UI centered, you can use them in manual written scripts and automations, we provide template lookup methods for that.

You can find those documented here:

<https://www.home-assistant.io/docs/configuration/templating/#devices>

As this issue has been resolved above, I'll go ahead and close this up on this end.


../Frenck
