### ISSUE TITLE
Callback Uri when using Casa

### ISSUE THREAD

**Issue by romufk** [home-assistant/home-assistant.github.io#23353]
### Feedback

Hi,

what is callback url when using Casa ?

Thanks

### URL

https://www.home-assistant.io/integrations/withings/

### Version

2022.7.3

**Comment by romufk** [comment]
Withings error : 

Logger: homeassistant.config_entries
Source: helpers/network.py:201
First occurred: 09:07:12 (2 occurrences)
Last logged: 09:07:30

Error setting up entry Franck for withings
Error setting up entry Sandra for withings
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/withings/__init__.py", line 130, in async_setup_entry
    data_manager = await async_get_data_manager(hass, entry)
  File "/usr/src/homeassistant/homeassistant/components/withings/common.py", line 1047, in async_get_data_manager
    url=webhook.async_generate_url(
  File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 73, in async_generate_url
    get_url(hass, prefer_external=True, allow_cloud=False),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 201, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

**Comment by frenck** [comment]
`https://my.home-assistant.io/redirect/oauth`

No matter what one is using. Please be sure to run the latest version of Home Assistant.

If you have more support questions, please use our community forums or Discord chat; see:

https://www.home-assistant.io/help

👍 

../Frenck
