### ISSUE TITLE
Error setting up entry xxx for tankerkoenig

### ISSUE THREAD

**Issue by totti4ever** [home-assistant/home-assistant.github.io#23767]
### Feedback

Hey there, after setting it up, everything worked like a charme.

Just like after some time (hours) it stopped with the following error in the log file:
```
Logger: homeassistant.config_entries
Source: components/tankerkoenig/__init__.py:188
First occurred: August 13, 2022 at 11:20:58 PM (4 occurrences)
Last logged: 5:35:38 PM

    Error setting up entry Tankstellen-home for tankerkoenig
    Error setting up entry Tankstellen-work for tankerkoenig
```

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/local/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/local/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/tankerkoenig/__init__.py", line 128, in async_setup_entry
    setup_ok = await hass.async_add_executor_job(coordinator.setup)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/tankerkoenig/__init__.py", line 188, in setup
    station_data = pytankerkoenig.getStationData(self._api_key, station_id)
  File "/usr/local/lib/python3.10/site-packages/pytankerkoenig/__init__.py", line 14, in getStationData
    return retrieveData(stationFullurl)
  File "/usr/local/lib/python3.10/site-packages/pytankerkoenig/__init__.py", line 36, in retrieveData
    response = request.urlopen(url)
  File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/local/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Try again>
```

After I reloaded the integration a couple of times, one of the two configs started to work again - the other is still faulty.

Any ideas about what to do or which information I should provide in addition?

p.s. great integration!!!

### URL

https://www.home-assistant.io/integrations/tankerkoenig/

### Version

2022.8.4

**Comment by mib1185** [comment]
Hi @totti4ever 

the error message "urlopen error [Errno -3] Try again" indicates an DNS issue on your system 🤔 
If this issue still persists, please check if your HomeAssistant system is able to resolve `creativecommons.tankerkoenig.de`

**Comment by totti4ever** [comment]
Okay, I found out what happened :-o

I had my wifi AP assigned the same IP as the HASS Container, I guess that's why packages got lost. Now I have numbers for the gas prices again

P.S.: I didn't have any issues when executing into the contaier and doing nslookups
