### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by thwe1966** [home-assistant/home-assistant.github.io#24166]
### Feedback

After installing and configuring the platform, I am not getting any entities -> error setting up on the integrations page.

A call to the API with my API key using:
https://creativecommons.tankerkoenig.de/json/list.php?lat=48.1506496&lng=10.8097448&rad=10&sort=price&type=diesel&apikey=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
results in an immediate response, so my key is OK (and also entered correctly!)

![image](https://user-images.githubusercontent.com/52085361/190896399-5b350c77-f168-4275-811d-8eb68280e209.png)

What is the problem?

### URL

https://www.home-assistant.io/integrations/tankerkoenig/

### Version

2022.9.4

### Additional information

**Error protocol details**

Logger: aiohttp.server
Source: components/tankerkoenig/config_flow.py:38
First occurred: 11:45:33 (4 occurrences)
Last logged: 11:45:43

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 216, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 225, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/components/tankerkoenig/config_flow.py", line 266, in async_step_init
    nearby_stations = await async_get_nearby_stations(
  File "/usr/src/homeassistant/homeassistant/components/tankerkoenig/config_flow.py", line 38, in async_get_nearby_stations
    return await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pytankerkoenig/__init__.py", line 22, in getNearbyStations
    return retrieveData(stationFullurl)
  File "/usr/local/lib/python3.10/site-packages/pytankerkoenig/__init__.py", line 36, in retrieveData
    response = request.urlopen(url)
  File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable

**Comment by frenck** [comment]
> urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable

That is an integration issue. Either in the integration itself of upstream with the service provider. However, you have submitted documentation feedback, which is not really a place where we can address issues with core integration.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
