### ISSUE TITLE
Can't install final stage

### ISSUE THREAD

**Issue by TCAby** [home-assistant/home-assistant.github.io#24464]
### Feedback

Final part of my log:
===============================
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      
              =============================DEBUG ASSISTANCE==========================
              If you are seeing an error here please try the following to
              successfully install cryptography:
      
              Upgrade to the latest pip and try again. This will fix errors for most
              users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
              =============================DEBUG ASSISTANCE==========================
      
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 17, in <module>
          from setuptools_rust import RustExtension
        File "/tmp/pip-build-env-5sxo4v4x/overlay/local/lib/python3.10/dist-packages/setuptools_rust/__init__.py", line 1, in <module>
          from .build import build_rust
        File "/tmp/pip-build-env-5sxo4v4x/overlay/local/lib/python3.10/dist-packages/setuptools_rust/build.py", line 23, in <module>
          from setuptools.command.build import build as CommandBuild  # type: ignore[import]
      ModuleNotFoundError: No module named 'setuptools.command.build'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
homeassistant@HAserver:/root$ hass
bash: hass: command not found
homeassistant@HAserver:/root$ 

================================
I checked python-dev and other packets, it looks correct. Repeated three times, tried to remove 'homeassistant' user and starting from the first step. Results the same...

### URL

https://www.home-assistant.io/installation/linux#install-home-assistant-core

### Additional information

My OS is Debian 11 Bullseye, i386 system

root@HAserver:~# sudo apt-get install -y python3 python3-dev python3-venv python3-pip bluez libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 libturbojpeg0-dev tzdata
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3 is already the newest version (3.10.6-1).
python3 set to manually installed.
python3-dev is already the newest version (3.10.6-1).
python3-dev set to manually installed.
python3-pip is already the newest version (22.2+dfsg-1).
libffi-dev is already the newest version (3.4.2-4).
libssl-dev is already the newest version (3.0.5-2).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-4.1).
build-essential is already the newest version (12.9).
libopenjp2-7 is already the newest version (2.5.0-1).
libopenjp2-7 set to manually installed.
libtiff5 is already the newest version (4.4.0-4).
libtiff5 set to manually installed.
tzdata is already the newest version (2022d-1).
The following additional packages will be installed:
  automake autotools-dev libjpeg62-turbo-dev libturbojpeg0 m4
Suggested packages:
  autoconf-archive gnu-standards autoconf-doc libtool gettext
  pulseaudio-module-bluetooth m4-doc
The following NEW packages will be installed:
  autoconf automake autotools-dev bluez libjpeg-dev libjpeg62-turbo-dev
  libturbojpeg0 libturbojpeg0-dev m4 python3-venv
0 upgraded, 10 newly installed, 0 to remove and 0 not upgraded.
Need to get 3,511 kB of archives.
After this operation, 12.0 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main i386 bluez i386 5.65-1 [1,138 kB]
Get:2 http://deb.debian.org/debian bookworm/main i386 m4 i386 1.4.19-1 [297 kB]
Get:3 http://deb.debian.org/debian bookworm/main i386 autoconf all 2.71-2 [343 kB]
Get:4 http://deb.debian.org/debian bookworm/main i386 autotools-dev all 20220109.1 [51.6 kB]
Get:5 http://deb.debian.org/debian bookworm/main i386 automake all 1:1.16.5-1.3 [823 kB]
Get:6 http://deb.debian.org/debian bookworm/main i386 libjpeg62-turbo-dev i386 1:2.1.2-1+b1 [308 kB]
Get:7 http://deb.debian.org/debian bookworm/main i386 libjpeg-dev i386 1:2.1.2-1+b1 [75.0 kB]
Get:8 http://deb.debian.org/debian bookworm/main i386 libturbojpeg0 i386 1:2.1.2-1+b1 [218 kB]
Get:9 http://deb.debian.org/debian bookworm/main i386 libturbojpeg0-dev i386 1:2.1.2-1+b1 [255 kB]
Get:10 http://deb.debian.org/debian bookworm/main i386 python3-venv i386 3.10.6-1 [1,188 B]
Fetched 3,511 kB in 1s (6,447 kB/s)
Selecting previously unselected package bluez.
(Reading database ... 120244 files and directories currently installed.)
Preparing to unpack .../0-bluez_5.65-1_i386.deb ...
Unpacking bluez (5.65-1) ...
Selecting previously unselected package m4.
Preparing to unpack .../1-m4_1.4.19-1_i386.deb ...
Unpacking m4 (1.4.19-1) ...
Selecting previously unselected package autoconf.
Preparing to unpack .../2-autoconf_2.71-2_all.deb ...
Unpacking autoconf (2.71-2) ...
Selecting previously unselected package autotools-dev.
Preparing to unpack .../3-autotools-dev_20220109.1_all.deb ...
Unpacking autotools-dev (20220109.1) ...
Selecting previously unselected package automake.
Preparing to unpack .../4-automake_1%3a1.16.5-1.3_all.deb ...
Unpacking automake (1:1.16.5-1.3) ...
Selecting previously unselected package libjpeg62-turbo-dev:i386.
Preparing to unpack .../5-libjpeg62-turbo-dev_1%3a2.1.2-1+b1_i386.deb ...
Unpacking libjpeg62-turbo-dev:i386 (1:2.1.2-1+b1) ...
Selecting previously unselected package libjpeg-dev:i386.
Preparing to unpack .../6-libjpeg-dev_1%3a2.1.2-1+b1_i386.deb ...
Unpacking libjpeg-dev:i386 (1:2.1.2-1+b1) ...
Selecting previously unselected package libturbojpeg0:i386.
Preparing to unpack .../7-libturbojpeg0_1%3a2.1.2-1+b1_i386.deb ...
Unpacking libturbojpeg0:i386 (1:2.1.2-1+b1) ...
Selecting previously unselected package libturbojpeg0-dev:i386.
Preparing to unpack .../8-libturbojpeg0-dev_1%3a2.1.2-1+b1_i386.deb ...
Unpacking libturbojpeg0-dev:i386 (1:2.1.2-1+b1) ...
Selecting previously unselected package python3-venv.
Preparing to unpack .../9-python3-venv_3.10.6-1_i386.deb ...
Unpacking python3-venv (3.10.6-1) ...
Setting up m4 (1.4.19-1) ...
Setting up libturbojpeg0:i386 (1:2.1.2-1+b1) ...
Setting up libturbojpeg0-dev:i386 (1:2.1.2-1+b1) ...
Setting up bluez (5.65-1) ...
Created symlink /etc/systemd/system/dbus-org.bluez.service → /lib/systemd/system/bluetooth.service.
Created symlink /etc/systemd/system/bluetooth.target.wants/bluetooth.service → /lib/systemd/system/bluetooth.service.
Setting up autotools-dev (20220109.1) ...
Setting up python3-venv (3.10.6-1) ...
Setting up libjpeg62-turbo-dev:i386 (1:2.1.2-1+b1) ...
Setting up autoconf (2.71-2) ...
Setting up automake (1:1.16.5-1.3) ...
update-alternatives: using /usr/bin/automake-1.16 to provide /usr/bin/automake (automake) in auto mode
Setting up libjpeg-dev:i386 (1:2.1.2-1+b1) ...
Processing triggers for dbus (1.14.4-1) ...
Processing triggers for libc-bin (2.35-2) ...
Processing triggers for man-db (2.10.2-3) ...
root@HAserver:~# sudo useradd -rm homeassistant
root@HAserver:~# sudo mkdir /srv/homeassistant
root@HAserver:~# sudo chown homeassistant:homeassistant /srv/homeassistant
root@HAserver:~# sudo -u homeassistant -H -s
cd /srv/homeassistant
python3 -m venv .
source bin/activate
homeassistant@HAserver:/root$ python3 -m pip install wheel
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.37.1)
homeassistant@HAserver:/root$ pip3 install homeassistant
Defaulting to user installation because normal site-packages is not writeable
Collecting homeassistant
  Downloading homeassistant-2022.10.1-py3-none-any.whl (19.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 9.6 MB/s eta 0:00:00
Collecting lru-dict==1.1.8
  Downloading lru_dict-1.1.8-cp310-cp310-manylinux_2_5_i686.manylinux1_i686.manylinux_2_17_i686.manylinux2014_i686.whl (27 kB)
Collecting bcrypt==3.1.7
  Downloading bcrypt-3.1.7.tar.gz (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.5/42.5 kB 5.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting home-assistant-bluetooth==1.3.0
  Downloading home_assistant_bluetooth-1.3.0-py3-none-any.whl (8.8 kB)
Requirement already satisfied: certifi>=2021.5.30 in /usr/lib/python3/dist-packages (from homeassistant) (2022.6.15)
Collecting ifaddr==0.1.7
  Downloading ifaddr-0.1.7-py2.py3-none-any.whl (10 kB)
Collecting httpx==0.23.0
  Downloading httpx-0.23.0-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.8/84.8 kB 9.6 MB/s eta 0:00:00
Collecting cryptography==38.0.1
  Downloading cryptography-38.0.1.tar.gz (599 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 599.4/599.4 kB 10.4 MB/s eta 0:00:00
  Installing build dependencies ... done

**Comment by TCAby** [comment]
And I upgraded pip by instruction: Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      
              =============================DEBUG ASSISTANCE==========================
              If you are seeing an error here please try the following to
              successfully install cryptography:
      
              Upgrade to the latest pip and try again. This will fix errors for most
              users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip

**Comment by TCAby** [comment]
And I upgraded pip by instruction: Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      
              =============================DEBUG ASSISTANCE==========================
              If you are seeing an error here please try the following to
              successfully install cryptography:
      
              Upgrade to the latest pip and try again. This will fix errors for most
              users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip

**Comment by TCAby** [comment]
I tried some times. I re-install wheel, Rust & Cargo... and as a result I've installed it! Bingo ))
