### ISSUE TITLE
Error after HA upgrade 0.42.4 on Windows 10

### ISSUE THREAD

**Issue by Newman82** [home-assistant/home-assistant.github.io#2479]
After upgrade to HA 0.42.4 I receive several errors in the log, this keep coming continusly. 

HA version: 0.42.4
Python version: 3.6.1

`17-04-23 07:02:04 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "C:\Users\Milestone\AppData\Roaming\.homeassistant\deps\aiohttp\web_protocol.py", line 417, in start
    resp = yield from self._request_handler(request)
  File "C:\Users\Milestone\AppData\Roaming\.homeassistant\deps\aiohttp\web.py", line 289, in _handle
    resp = yield from handler(request)
  File "c:\users\milestone\appdata\local\programs\python\python36\lib\asyncio\coroutines.py", line 213, in coro
    res = yield from res
  File "c:\users\milestone\appdata\local\programs\python\python36\lib\asyncio\coroutines.py", line 213, in coro
    res = yield from res
  File "c:\users\milestone\appdata\local\programs\python\python36\lib\site-packages\homeassistant\components\http\ban.py", line 58, in ban_middleware_handler
    return (yield from handler(request))
  File "c:\users\milestone\appdata\local\programs\python\python36\lib\site-packages\homeassistant\components\http\__init__.py", line 425, in handle
    result = yield from result
  File "c:\users\milestone\appdata\local\programs\python\python36\lib\site-packages\homeassistant\components\media_player\__init__.py", line 925, in get
    return web.Response(body=data, content_type=content_type)
  File "C:\Users\Milestone\AppData\Roaming\.homeassistant\deps\aiohttp\web_response.py", line 444, in __init__
    raise ValueError("charset must not be in content_type "
ValueError: charset must not be in content_type argument
`

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant documentation. 

Please report Home Assistant bugs at https://github.com/home-assistant/home-assistant/issues/new, for other issues please use our [forum](https://community.home-assistant.io/).
