### ISSUE TITLE
Samsung Family Hub - Camera

### ISSUE THREAD

**Issue by bearhntr** [home-assistant/home-assistant.github.io#24862]
### Feedback

The instructions here are severely lacking.  For example - are the " " required for the IP Address?  

I have tried both and cannot seem to get anything but errors (see below).  Also would be very helpful if there was more information "HOW" to use this configuration and setup.  

```
Logger: aiohttp.server
Source: components/familyhub/camera.py:55
First occurred: November 7, 2022 at 17:06:27 (1 occurrences)
Last logged: November 7, 2022 at 17:06:27

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 722, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 740, in handle
    image = await _async_get_image(
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 169, in _async_get_image
    if image_bytes := await camera.async_camera_image(
  File "/usr/src/homeassistant/homeassistant/components/familyhub/camera.py", line 55, in async_camera_image
    return await self.family_hub_cam.async_get_cam_image()
  File "/usr/local/lib/python3.10/site-packages/pyfamilyhublocal/__init__.py", line 29, in async_get_cam_image
    glazeCameraInfo = await self._get_cam_info()
  File "/usr/local/lib/python3.10/site-packages/pyfamilyhublocal/__init__.py", line 52, in _get_cam_info
    async with async_timeout.timeout(5, loop=self._loop):
TypeError: timeout() got an unexpected keyword argument 'loop'
```

### URL

https://www.home-assistant.io/integrations/familyhub

### Version

Home Assistant 2022.10.5/Supervisor 2022.10.2/Operating System 9.3/Frontend 20221010.0 - latest

### Additional information

From the SmartThings IDE page:

```
<html>
<body>
<!--StartFragment--><h1 style="box-sizing: border-box; font-size: 1.5em; margin: 0px; font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif; font-weight: normal; line-height: 1.1; color: rgb(33, 123, 213); padding: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(243, 243, 243); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">[refrigerator] Samsung (LCD) Device<span> </span><em style="box-sizing: border-box;">Family Hub</em></h1><div class="table-wrap" style="box-sizing: border-box; position: static; width: 1843px; overflow: auto; color: rgb(102, 102, 102); font-family: HelveticaNeue-Light, &quot;Helvetica Neue Light&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Lucida Grande&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(243, 243, 243); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Name | [refrigerator] Samsung (LCD)
-- | --
Label | Family Hub
Type | placeholder
Version | Published
Status | ONLINE
Group | Kitchen
Last Activity At | 2022-11-08 8:31 AM EST
Date Created | 2022-10-26 10:42 PM EDT
Last Updated | 2022-10-26 11:04 PM EDT
Data | No data found for device
Current States | No states found
Execution Location | Cloud
Events | List Events
Child Devices | coolercvroomfreezericemakericemaker-02pantry-01scale-10scale-11
In Use By |  

</div><!--EndFragment-->
</body>
</html>[refrigerator] Samsung (LCD) Device Family Hub
Name	[refrigerator] Samsung (LCD)
Label	Family Hub
Type	placeholder
Version	Published
Status	ONLINE
Group	[Kitchen](https://graph-na04-useast2.api.smartthings.com/group/show/dfc3148a-45b2-4ec9-b560-b06197b1cb4c)
Last Activity At	2022-11-08 8:31 AM EST
Date Created	2022-10-26 10:42 PM EDT
Last Updated	2022-10-26 11:04 PM EDT
Data	No data found for device
Current States	No states found
Execution Location	Cloud
Events	[List Events](https://graph-na04-useast2.api.smartthings.com/device/9fead421-f09f-17be-0703-2a805cd4a3fa/events)
Child Devices	
[cooler](https://graph-na04-useast2.api.smartthings.com/device/show/cd83c4f6-8b96-4987-9ae2-4e4e2443b6ef)
[cvroom](https://graph-na04-useast2.api.smartthings.com/device/show/8c92a23c-6dc5-4e7a-8bb3-5d7121b20da3)
[freezer](https://graph-na04-useast2.api.smartthings.com/device/show/1d56a1e5-5d76-4f03-bde1-2cf03f364222)
[icemaker](https://graph-na04-useast2.api.smartthings.com/device/show/dbe527c4-d91d-4778-83a4-f21f5d5f60b0)
[icemaker-02](https://graph-na04-useast2.api.smartthings.com/device/show/1ed975ec-49c0-4046-9255-60b12b68df14)
[pantry-01](https://graph-na04-useast2.api.smartthings.com/device/show/54d92214-f7ab-48d0-8a94-8fa24c5fd16e)
[scale-10](https://graph-na04-useast2.api.smartthings.com/device/show/06af6132-660a-494c-991b-5dcd9421b569)
[scale-11](https://graph-na04-useast2.api.smartthings.com/device/show/3517ae38-dd43-4d84-b024-bde3902b82de)
In Use By
```

**Comment by bearhntr** [comment]
SEEMS TO BE THE COMMON ANSWER THESE DAYS --  "NOT PLANNED"  -- when there was neve a SINGLE RESPONSE to the posting.
