### ISSUE TITLE
export VLC_PLUGIN_PATH=$VLC_PLUGIN_PATH:/Applications/VLC.app/Contents/MacOS/plugins doesn't work on macOS Monterrey

### ISSUE THREAD

**Issue by racedo** [home-assistant/home-assistant.github.io#25243]
### Feedback

I tried this and it has a hard time looking for libvlccore.dylib.

I added a symlink to bypass the issue with loading libvlccore.dylib:

`ln -sf /System/Volumes/Data/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib /opt/homebrew/lib/`

Then the error changed to:

```
2022-12-11 17:15:13.451 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up vlc platform for media_player
Traceback (most recent call last):
  File "/Users/racedoro/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/racedoro/homeassistant/lib/python3.10/site-packages/homeassistant/components/vlc/media_player.py", line 48, in setup_platform
    [VlcDevice(config.get(CONF_NAME, DEFAULT_NAME), config.get(CONF_ARGUMENTS))]
  File "/Users/racedoro/homeassistant/lib/python3.10/site-packages/homeassistant/components/vlc/media_player.py", line 69, in __init__
    self._vlc = self._instance.media_player_new()
AttributeError: 'NoneType' object has no attribute 'media_player_new'
```

Any help appreciated.

### URL

http://localhost:8123/developer-tools/yaml

### Version

Home Assistant 2022.12.1

**Comment by racedo** [comment]
Ok, the fix for me was to use .zshenv instead of .bashrc, as that's the default in MacOS Sierra and have the lib/ and plugins/ directories in it:
```
% cat ~/.zshenv
export VLC_PLUGIN_PATH=/Applications/VLC.app/Contents/MacOS/lib/:/Applications/VLC.app/Contents/MacOS/plugins/
```
