### ISSUE TITLE
Error in HA after configure Supla

### ISSUE THREAD

**Issue by kzajac83** [home-assistant/home-assistant.github.io#25304]
### Feedback

Hello.  

I made according instruction intergariotn HA with Supla and add to configure (not sure where, begging , middle or end of configure file) below config (access string and server string change some characters)

supla:
  servers:
    - server: svr16.supla.org
      access_token: YjM3Mj30Zme4ZGVlNDk2NmY4NWVjZTUzYWU4tt4tMTQxYzJiNzA3ODk4ZjFlYertNzM5NmJhNDgxYmM4MjI4Ng.aHR0cHM6Ly9zdnI4Ni5zddgfYS5vcmc=

After save config and check config all is fine but after reboot got:
`Logger: homeassistant.setup
Source: components/supla/__init__.py:127
First occurred: 00:46:59 (1 occurrences)
Last logged: 00:46:59

Error during setup of component supla
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/src/homeassistant/homeassistant/components/supla/__init__.py", line 90, in async_setup
    await discover_devices(hass, base_config)
  File "/usr/src/homeassistant/homeassistant/components/supla/__init__.py", line 127, in discover_devices
    for channel_id, channel in coordinator.data.items():
AttributeError: 'NoneType' object has no attribute 'items'
`

And:
`Logger: homeassistant.components.supla
Source: components/supla/__init__.py:108
Integration: supla (documentation, issues)
First occurred: 00:46:59 (1 occurrences)
Last logged: 00:46:59

Unexpected error fetching supla-svr86.supla.org data: string indices must be integers
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/usr/src/homeassistant/homeassistant/components/supla/__init__.py", line 107, in _fetch_channels
    channels = {
  File "/usr/src/homeassistant/homeassistant/components/supla/__init__.py", line 108, in <dictcomp>
    channel["id"]: channel
TypeError: string indices must be integers
`

### URL

https://www.home-assistant.io/integrations/supla

### Version

2022.11.5

**Comment by frenck** [comment]
Hi there @kzajac83 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 🤗 

../Frenck
