### ISSUE TITLE
LG TV not connecting on WebOS Versiob 3.30.14

### ISSUE THREAD

**Issue by derbohmann** [home-assistant/home-assistant.github.io#25774]
### Feedback

When I updated my LG TV to the new Version 3.30.14 homeassistant stopped getting information about the state of the TV. I decided to remove the device to pair it again. Sadly I'm not able to pair the device again.
I have tried it in YAML and UI Mode. I also changed the IP Address of the TV to maybe solve any caching issues.

In the log I can find the following message:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/client.py", line 138, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/http.py", line 120, in read_response
    status_line = await read_line(stream)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/http.py", line 194, in read_line
    line = await stream.readline()
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 525, in readline
    line = await self.readuntil(sep)
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 617, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 502, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 854, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer`

### URL

https://www.home-assistant.io/integrations/webostv/

### Version

2023.1.4

**Comment by thecode** [comment]
In `2023.1.4` there was a change that break connection for older firmware. This is fixed and will be included in `2023.1.5`.
In any case this is a place for documentations issues, if you still have issues in `2023.1.5` please create an issue in [Home Assistant Core Repository](https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml).
