### ISSUE TITLE
Windows Token Extractor Tool Error

### ISSUE THREAD

**Issue by cihanulusoy** [home-assistant/home-assistant.github.io#25976]
### Feedback

The token_extractor.exe found at https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/releases/latest/download/token_extractor.exe gives the following error:

Traceback (most recent call last):
  File "site-packages\requests\compat.py", line 11, in <module>
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "token_extractor.py", line 11, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "site-packages\requests\__init__.py", line 45, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "site-packages\requests\exceptions.py", line 9, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "site-packages\requests\compat.py", line 13, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "site-packages\charset_normalizer\__init__.py", line 24, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "site-packages\charset_normalizer\api.py", line 5, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "site-packages\charset_normalizer\cd.py", line 9, in <module>
ModuleNotFoundError: No module named 'charset_normalizer.md__mypyc'
[15272] Failed to execute script token_extractor

Could you help please?

### URL

https://www.home-assistant.io/integrations/xiaomi_ble/

### Version

2023.1.7

**Comment by Jc2k** [comment]
Hi! Sorry you are struggling.
Unfortunately the homeassistant GitHub is the wrong place to get help with this tool. We didn't write the tool, we can't help you with it. Personally, I don't even have windows so I couldn't help you even if I had time. 

If the author of the tool isn't able to help you, you might be able to find help in the community forums from other users.
