### ISSUE TITLE
Synology integration seems broken after update

### ISSUE THREAD

**Issue by latez** [home-assistant/home-assistant.github.io#26105]
### Feedback

Logger: homeassistant.config_entries
Source: components/synology_dsm/common.py:94
First occurred: 7:57:46 PM (3 occurrences)
Last logged: 9:22:48 PM

Error setting up entry Nemesis for synology_dsm
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/synology_dsm/__init__.py", line 68, in async_setup_entry
    await api.async_setup()
  File "/usr/src/homeassistant/homeassistant/components/synology_dsm/common.py", line 94, in async_setup
    await self.dsm.surveillance_station.update()
  File "/usr/local/lib/python3.10/site-packages/synology_dsm/api/surveillance_station/__init__.py", line 25, in update
    raw_data = await self._dsm.get(self.CAMERA_API_KEY, "List", max_version=7)
  File "/usr/local/lib/python3.10/site-packages/synology_dsm/synology_dsm.py", line 207, in get
    return await self._request("GET", api, method, params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/synology_dsm/synology_dsm.py", line 282, in _request
    response = await self._execute_request(request_method, url, params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/synology_dsm/synology_dsm.py", line 308, in _execute_request
    response = await self._session.get(url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 919, in get
    self._request(hdrs.METH_GET, url, allow_redirects=allow_redirects, **kwargs)
TypeError: ClientSession._request() got an unexpected keyword argument 'max_version'

In addition - 

Logger: homeassistant.components.synology_dsm.config_flow
Source: components/synology_dsm/config_flow.py:328
Integration: Synology DSM (documentation, issues)
First occurred: 9:22:28 PM (4 occurrences)
Last logged: 9:22:37 PM

{'api': None, 'code': -1, 'reason': 'Unknown', 'details': 'ClientError = Bad Request'}

### URL

https://www.home-assistant.io/integrations/synology_dsm/

### Version

2023.2.1

**Comment by frenck** [comment]
Hi there @latez 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍

../Frenck
