### ISSUE TITLE
Osram Lighity Error since 0.44.1

### ISSUE THREAD

**Issue by peterking99** [home-assistant/home-assistant.github.io#2696]
Got Problems since HA 0.44.1 with Osram Lightify:

2017-05-23 17:25:16 WARNING (Thread-8) [homeassistant.components.emulated_hue] Alexa type is deprecated and will be removed in afuture version
2017-05-23 17:25:18 ERROR (MainThread) [homeassistant.components.light] Error while setting up platform osramlightify
Traceback (most recent call last):
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 155, in _async_setup_platform
    entity_platform.schedule_add_entities, discovery_info
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/light/osramlightify.py", line 60, in setup_platform
    setup_bridge(bridge, add_devices, add_groups)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/light/osramlightify.py", line 106, in setup_bridge
    update_lights()
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/util/__init__.py", line 303, in wrapper
    result = method(*args, **kwargs)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/util/__init__.py", line 303, in wrapper
    result = method(*args, **kwargs)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/light/osramlightify.py", line 97, in update_lights
    update_lights)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/light/osramlightify.py", line 268, in __init__
    super().__init__(group, update_lights)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/light/osramlightify.py", line 121, in __init__
    self.update()
  File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/light/osramlightify.py", line 282, in update
    light = self._bridge.lights()[self._light_ids[0]]
IndexError: list index out of range

Anybody issus?

BG

**Comment by MartinHjelmare** [comment]
This is the issue tracker for the home assistant docs. Issues with home assistant should be reported here:
https://github.com/home-assistant/home-assistant/issues
