### ISSUE TITLE
Simplisafe

### ISSUE THREAD

**Issue by Hrtlnd549** [home-assistant/home-assistant.github.io#27009]
### Feedback

I have tried to install the Simplisafe integration. Whenever I add the callback code I receive an error message stating 

Logger: homeassistant.config_entries
Source: components/simplisafe/__init__.py:357
First occurred: 4:03:16 PM (1 occurrences)
Last logged: 4:03:16 PM

Error setting up entry 3949646 for simplisafe
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/lib/python3.10/site-packages/homeassistant/components/simplisafe/__init__.py", line 357, in async_setup_entry
    api = await API.async_from_refresh_token(
  File "/usr/lib/python3.10/site-packages/simplipy/api.py", line 154, in async_from_refresh_token
    await api.async_refresh_access_token()
  File "/usr/lib/python3.10/site-packages/simplipy/api.py", line 406, in async_refresh_access_token
    self._save_token_data_from_response(token_data)
  File "/usr/lib/python3.10/site-packages/simplipy/api.py", line 258, in _save_token_data_from_response
    self.refresh_token = token_data["refresh_token"]
KeyError: 'refresh_token'

### URL

https://www.home-assistant.io/integrations/simplisafe/

### Version

2023.4.4

**Comment by bachya** [comment]
Thanks for your input! This is the documentation repository; for issues with HA Core, please post here: https://github.com/home-assistant/core/issues

Separately, this issue was filed in https://github.com/home-assistant/core/issues/90870 and fixed in HA 2023.4.1; please upgrade to that version.

**Comment by Hrtlnd549** [comment]
Thank you Bachya
