### ISSUE TITLE
Ecowitt Unknown error occurred

### ISSUE THREAD

**Issue by The5eeker** [home-assistant/home-assistant.github.io#27350]
### Feedback

HA 2023.5 messed up the Hacs Ecowitt install.  I had Ecowitt through HACS, then the May update of home assistant came out and borked my hacs version of Ecowitt, I couldn’t even uninstall it. I had to revert back the the previous version of Home Assistant, then uninstall it, then install the home assistant version of Ecowitt, then update to the May version of HA again and all was fine, for a short time. A few hours later I wasn’t getting data from my weather station again and Ecowitt was giving me a gateway error or something so I uninstalled it but when I tried to reinstall it it gave me the error "Unknown error occurred".  I don't know how to fix this error.  I've tried rebooting the server HA is running on, I'm using the HA OS on a dedicated mini PC.  I don't know anything about Linux.

### URL

https://www.home-assistant.io/integrations/ecowitt/

### Version

2023.5.1

**Comment by pvizeli** [comment]
The core does not support custom integrations. Please open an issue at your custom integration

**Comment by elitistphoenix** [comment]
![Screenshot_2023-05-13_13-24-33](https://github.com/home-assistant/home-assistant.io/assets/20254357/95a16f29-c1cb-49a0-8522-2fc4f8b5eacb)
Not sure this is related to HACS

**Comment by The5eeker** [comment]
You are right, this isn't through HACS.  HA has its own Ecowitt integration now.  I had to uninstall the HACS version after the May 2023 update because the HACS version didn't work anymore.  Now the Home Assistant version quit working and I haven't been able to reinstall it.  I get the same error you do, my ticket was closed though.

Below is log info that shows up after I try to add Ecowitt.

Logger: aiohttp.server
Source: helpers/network.py:200
First occurred: 4:33:36 PM (91 occurrences)
Last logged: 5:03:05 PM
Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/components/ecowitt/config_flow.py", line 35, in async_step_user
    base_url = URL(get_url(self.hass))
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 200, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

**Comment by elitistphoenix** [comment]
@pvizeli could you please re-open this issue? I don't believe it's HACs related.

**Comment by klaasnicolaas** [comment]
This issue belongs in the [core](https://github.com/home-assistant/core) repository, we use the issue tracker here for documentation not for integration issues.

./Klaas
