### ISSUE TITLE
Fitbit sensors not working anymore

### ISSUE THREAD

**Issue by Atarinside** [home-assistant/home-assistant.github.io#27388]
### Feedback

I changed nothing but my fitbit sensor are not working anymore since ~2 weeks.

My sensor.yaml :

```
- platform: fitbit
  clock_format: 24H
  monitored_resources:
    - "body/weight"
    - "body/bmi"
    - "body/fat"
    - "devices/battery"
```
Logfile:

`2023-05-12 11:01:55.702 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up fitbit platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/fitbit/sensor.py", line 193, in setup_platform
    authd_client.client.refresh_token()
  File "/usr/local/lib/python3.10/site-packages/fitbit/api.py", line 156, in refresh_token
    token = self.session.refresh_token(
  File "/usr/local/lib/python3.10/site-packages/requests_oauthlib/oauth2_session.py", line 452, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 427, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) 
2023-05-12 11:02:00.139 ERROR (MainThread) [aiohttp.server] Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1205, in _sendfile_fallback
    read = await self.run_in_executor(None, file.readinto, view)
asyncio.exceptions.CancelledError`

### URL

https://www.home-assistant.io/integrations/fitbit/

### Version

2023.5.2

**Comment by dannytsang** [comment]
Hi @Atarinside

This looks to be a system related issue rather than a documentation one (which is this repository). Can you raise this by going to **New issue** > **Report a bug/issue with Home Assistant Core itself** please.

**Comment by mortenalbring** [comment]
I have the same issue. Was there ever a resolution on this?

**Comment by Atarinside** [comment]
> I have the same issue. Was there ever a resolution on this?

I raised another issue about it as requested above: https://github.com/home-assistant/core/issues/93454
But no answers yet.

**Comment by klaasnicolaas** [comment]
Please continue this discussion in core, we use the issue tracker here for documentation feedback.
