### ISSUE TITLE
the clementine cant run on current HA version

### ISSUE THREAD

**Issue by nielsnl68** [home-assistant/home-assistant.github.io#27562]
### Feedback

I tried to use above media-player but failed.

### URL

https://www.home-assistant.io/integrations/clementine/

### Version

2023.5.4

### Additional information

Here is the systemlog info:

```
Logger: homeassistant.loader
Source: components/clementine/media_player.py:7
First occurred: 19:40:49 (2 occurrences)
Last logged: 19:43:05

Unexpected exception importing platform homeassistant.components.clementine.media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/src/homeassistant/homeassistant/components/clementine/media_player.py", line 7, in <module>
    from clementineremote import ClementineRemote
  File "/usr/local/lib/python3.10/site-packages/clementineremote/__init__.py", line 17, in <module>
    from .clementine import ClementineRemote
  File "/usr/local/lib/python3.10/site-packages/clementineremote/clementine.py", line 21, in <module>
    import clementineremote.remotecontrolmessages_pb2 as cr
  File "/usr/local/lib/python3.10/site-packages/clementineremote/remotecontrolmessages_pb2.py", line 32, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by frenck** [comment]
Hi there @nielsnl68 👋 

It seems like you wanted to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
