### ISSUE TITLE
heatgenuis not working anymore

### ISSUE THREAD

**Issue by garrathbond** [home-assistant/home-assistant.github.io#27634]
### Feedback

How do I fix this?
Logger: homeassistant.setup
Source: components/geniushub/__init__.py:124
First occurred: 19:37:12 (1 occurrences)
Last logged: 19:37:12

Error during setup of component geniushub
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 257, in _async_setup_component
    result = await task
  File "/usr/src/homeassistant/homeassistant/components/geniushub/__init__.py", line 124, in async_setup
    await client.update()
  File "/usr/local/lib/python3.10/site-packages/geniushubclient/__init__.py", line 260, in update
    super().update()  # now parse all the JSON
  File "/usr/local/lib/python3.10/site-packages/geniushubclient/__init__.py", line 201, in update
    self.issues = [convert_issue(raw_json) for raw_json in self._issues]
  File "/usr/local/lib/python3.10/site-packages/geniushubclient/__init__.py", line 201, in <listcomp>
    self.issues = [convert_issue(raw_json) for raw_json in self._issues]
  File "/usr/local/lib/python3.10/site-packages/geniushubclient/__init__.py", line 161, in convert_issue
    device_type = self.device_by_id[raw_json["data"]["nodeID"]].data["type"]
KeyError: '8'

### URL

https://www.home-assistant.io/integrations/geniushub/

### Version

2023.5.4

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
