### ISSUE TITLE
Following instructions leads to failing ESPHome update of the Atom Echo

### ISSUE THREAD

**Issue by m5ck** [home-assistant/home-assistant.github.io#29353]
### Feedback

Following these instructions allows you to successfully add the Atom Echo to the ESPHome Plugin on Home Assistant 2023.10.3 as a device. ESPHome then suggest an update, which fails with the error messages below:

```
INFO ESPHome 2023.9.3
INFO Reading configuration /config/esphome/m5stack-atom-echo-.......yaml...
ERROR Unexpected exception while reading configuration:
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/esphome/esphome/__main__.py", line 1036, in main
    return run_esphome(sys.argv)
  File "/esphome/esphome/__main__.py", line 1014, in run_esphome
    config = read_config(dict(args.substitution) if args.substitution else {})
  File "/esphome/esphome/config.py", line 986, in read_config
    res = load_config(command_line_substitutions)
  File "/esphome/esphome/config.py", line 840, in load_config
    return _load_config(command_line_substitutions)
  File "/esphome/esphome/config.py", line 828, in _load_config
    result = validate_config(config, command_line_substitutions)
  File "/esphome/esphome/config.py", line 690, in validate_config
    substitutions.do_substitution_pass(config, command_line_substitutions)
  File "/esphome/esphome/components/substitutions/__init__.py", line 143, in do_substitution_pass
    config.move_to_end(CONF_SUBSTITUTIONS, False)
AttributeError: 'dict' object has no attribute 'move_to_end'
```

### URL

https://www.home-assistant.io/voice_control/thirteen-usd-voice-remote/

### Version

2023.10.3

**Comment by BeardedTinker** [comment]
This is probably due to trying to "update" with lower version of ESPHome - 2023.9.3 (vs 2023.10 - beta). Just avoid pressing update until you have ESPHome 2023.10 installed.

**Comment by mberkhof23** [comment]
@BeardedTinker  Afraid not, I experience the same and everything is up to date 2023.10.3, Supervisor 2023.10.0, OS 11.0. It works but but stops responding after a few commands.

**Comment by m5ck** [comment]
Issue is fixed with the last ESPhome update.
