### ISSUE TITLE
on Dec 9, 2023 this is failing to install 

### ISSUE THREAD

**Issue by kcossabo** [home-assistant/home-assistant.github.io#30240]
### Feedback

```
Error on Home Assistant

Logger: homeassistant.setup
Source: setup.py:251
First occurred: 10:13:54 AM (1 occurrences)
Last logged: 10:13:54 AM

Setup failed for custom integration 'ecowitt': Unable to import component: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 814, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/ecowitt/__init__.py", line 20, in <module>
    from homeassistant.helpers.entity_registry import (
ImportError: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)
```

### URL

https://www.home-assistant.io/integrations/ecowitt/

### Version

2023.12.1

**Comment by klaasnicolaas** [comment]
You are using a custom integration from ecowitt, which is why you must submit this issue to the maker of the custom integration.
