### ISSUE TITLE
I'm a new user trying to setup google assistant with home assistant, I followed the guide here:

### ISSUE THREAD

**Issue by monckey100** [home-assistant/home-assistant.github.io#30567]
I'm a new user trying to setup google assistant with home assistant, I followed the guide here:

https://www.home-assistant.io/integrations/google_assistant/

for manual setup, I managed to make my HA accessible externally and I'm on a static IP too...

so I tried to add my test project to my home app, and I get "could not reach [test] myapp" 

I investigated further, the homegraph API shows it's being hit, but when I check the google console logs I get the following:
(I replaced any identifier IDs with X's)
```
{
  "textPayload": "SYNC: Request ID XXXXXXXXXXX failed with code: CANCELLED",
  "insertId": "XXXXXXXX",
  "resource": {
    "type": "assistant_action",
    "labels": {
      "action_id": "SMART_HOME_SYNC",
      "project_id": "smart-home-XXXX",
      "version_id": ""
    }
  },
  "timestamp": "2023-12-28T02:24:59.503334965Z",
  "severity": "ERROR",
  "logName": "projects/smart-home-XXXX/logs/actions.googleapis.com%2Factions",
  "receiveTimestamp": "2023-12-28T02:24:59.512023784Z"
}
```

![image](https://github.com/home-assistant/core/assets/5633486/1b11e354-3ea9-4a1c-89b9-34beb4c56fa4)

![image](https://github.com/home-assistant/core/assets/5633486/66428a7a-a4f5-4b63-84ec-fa953323ee29)

```
2023-12-28 04:10:01.957 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:requestSync failed: 404
2023-12-28 04:10:01.957 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140279540392512] Unable to sync devices with result code: 404, check log for more info.
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/core.py", line 2067, in async_call
response_data = await coro
^^^^^^^^^^
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/core.py", line 2104, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/entity_component.py", line 272, in handle_service
return await service.entity_service_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 878, in entity_service_call
single_response = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/service.py", line 948, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/button/__init__.py", line 124, in _async_press_action
await self.async_press()
File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/google_assistant/button.py", line 57, in async_press
raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Unable to sync devices with result code: 404, check log for more info.
```

![image](https://github.com/home-assistant/core/assets/5633486/edf65a2e-415a-4b0d-9e05-b989d8187480)

_Originally posted by @monckey100 in https://github.com/home-assistant/core/issues/102128#issuecomment-1872447948_

**Comment by joelfriesecke** [comment]
I am receiving the same error messages.

I am also using Cloudflare and have already set up WAF rules, but unfortunately, without success.

**Comment by metallmanu** [comment]
same issues for me with DuckDNS

**Comment by idroyIT** [comment]
Same problem. Using my own domain through cloudflare DNS with NGINX. Followed the documentation. Getting message "Something went wrong" in Google Home app on iOS. And also the 404 errors on HomeGraph API.
