### ISSUE TITLE
Problem HA and Xiaomi AX3600 with OpenWRT

### ISSUE THREAD

**Issue by OdoMarTus** [home-assistant/home-assistant.github.io#31262]
### Feedback

I have this problem in HA:
2024-02-06 11:02:34.633 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 432, in async_device_tracker_scan
    found_devices = await scanner.async_scan_devices()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 952, in async_scan_devices
    return await self.hass.async_add_executor_job(self.scan_devices)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/luci/device_tracker.py", line 67, in scan_devices
    self._update_info()
  File "/usr/src/homeassistant/homeassistant/components/luci/device_tracker.py", line 94, in _update_info
    result = self.router.get_all_connected_devices(only_reachable=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openwrt_luci_rpc/__init__.py", line 42, in get_all_connected_devices
    return self.router.get_all_connected_devices(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openwrt_luci_rpc/openwrt_luci_rpc.py", line 178, in get_all_connected_devices
    device_entry['hostname'] = utilities.get_hostname_from_dhcp(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openwrt_luci_rpc/utilities.py", line 28, in get_hostname_from_dhcp
    host = [x for x in dhcp_result.values()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openwrt_luci_rpc/utilities.py", line 32, in 
    and x['mac'].upper() == mac]
        ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'upper'

### URL

https://www.home-assistant.io/integrations/luci/

### Version

2024.1.5

### Additional information

My config: https://www.home-assistant.io/integrations/luci/

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by OdoMarTus** [comment]
OK. Sorry
