### ISSUE TITLE
velux integration

### ISSUE THREAD

**Issue by tof92130** [home-assistant/home-assistant.github.io#31294]
### Feedback

with update 2024.2.0 velum integration seems to be KO :

Logger: homeassistant.setup
Source: setup.py:333
First occurred: 21:31:19 (1 occurrences)
Last logged: 21:31:19

Error during setup of component velux
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 333, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/velux/__init__.py", line 39, in async_setup
    await hass.data[DATA_VELUX].async_start()
  File "/usr/src/homeassistant/homeassistant/components/velux/__init__.py", line 84, in async_start
    await self.pyvlx.load_scenes()
  File "/usr/local/lib/python3.12/site-packages/pyvlx/pyvlx.py", line 106, in load_scenes
    await self.scenes.load()
  File "/usr/local/lib/python3.12/site-packages/pyvlx/scenes.py", line 56, in load
    await get_scene_list.do_api_call()
  File "/usr/local/lib/python3.12/site-packages/pyvlx/api/api_event.py", line 29, in do_api_call
    await self.pyvlx.check_connected()
  File "/usr/local/lib/python3.12/site-packages/pyvlx/pyvlx.py", line 83, in check_connected
    await self.connect()
  File "/usr/local/lib/python3.12/site-packages/pyvlx/pyvlx.py", line 58, in connect
    await self.connection.connect()
  File "/usr/local/lib/python3.12/site-packages/pyvlx/connection.py", line 103, in connect
    self.transport, _ = await self.loop.create_connection(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1146, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1179, in _create_connection_transport
    await waiter
ConnectionAbortedError: SSL handshake is taking longer than 60.0 seconds: aborting the connection

### URL

https://www.home-assistant.io/integrations/velux/

### Version

2024.2.0

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
