### ISSUE TITLE
airzone cloud error adding new device

### ISSUE THREAD

**Issue by luismipr** [home-assistant/home-assistant.github.io#32064]
### Feedback

we are trying to integrate an aerothermal boiler of the brand kosner ( midea ) but it gives an error when we add it using the version airzone cloud.
This is the error.

`Registrador: homeassistant.components.airzone_cloud.coordinator
Fuente: helpers/update_coordinator.py:318
integración: Airzone Cloud (documentación, problemas)
Ocurrió por primera vez: 25 de marzo de 2024, 06:42:46 (115 ocurrencias)
Último inicio de sesión: 22:55:36

Unexpected error fetching airzone_cloud data: float() argument must be a string or a real number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/airzone_cloud/coordinator.py", line 40, in _async_update_data
    await self.airzone.update()
  File "/usr/local/lib/python3.12/site-packages/aioairzone_cloud/cloudapi.py", line 840, in update
    await self._update()
  File "/usr/local/lib/python3.12/site-packages/aioairzone_cloud/cloudapi.py", line 828, in _update
    await self._update_polling()
  File "/usr/local/lib/python3.12/site-packages/aioairzone_cloud/cloudapi.py", line 807, in _update_polling
    await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.12/site-packages/aioairzone_cloud/cloudapi.py", line 634, in update_aidoos
    await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.12/site-packages/aioairzone_cloud/cloudapi.py", line 625, in update_aidoo
    await aidoo.update(update)
  File "/usr/local/lib/python3.12/site-packages/aioairzone_cloud/entity.py", line 116, in update
    self.update_data(update)
  File "/usr/local/lib/python3.12/site-packages/aioairzone_cloud/aidoo.py", line 91, in update_data
    super().update_data(update)
  File "/usr/local/lib/python3.12/site-packages/aioairzone_cloud/hvac.py", line 533, in update_data
    self.temp = float(local_temp[API_CELSIUS])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
`

Thx in advance

### URL

https://www.home-assistant.io/integrations/airzone/

### Version

2024.3.3

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
