### ISSUE TITLE
Cisco IOS component error after moving to Hassio

### ISSUE THREAD

**Issue by shiznic** [home-assistant/home-assistant.github.io#3238]
Appears there is an issue with using SSH to older Cisco devices requiring diffie-hellman-group1-sha1.  I am using a Cisco 3750 switch.  I was able to place a config file with an entry to force "KexAlgorithms +diffie-hellman-group1-sha1" and had this component working before moving to HASSIO.   Not sure what the work around is now.

Error from logs:

2017-08-24 12:14:58 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform cisco_ios
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pexpect/spawnbase.py", line 144, in read_nonblocking
    s = os.read(self.child_fd, size)
OSError: [Errno 5] I/O error
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pexpect/expect.py", line 97, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 455, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/usr/lib/python3.6/site-packages/pexpect/spawnbase.py", line 149, in read_nonblocking
    raise EOF('End Of File (EOF). Exception style platform.')
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/components/device_tracker/__init__.py", line 153, in async_setup_platform
    platform.get_scanner, hass, {DOMAIN: p_config})
  File "/usr/lib/python3.6/asyncio/futures.py", line 331, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/device_tracker/cisco_ios.py", line 33, in get_scanner
    scanner = CiscoDeviceScanner(config[DOMAIN])
  File "/usr/lib/python3.6/site-packages/homeassistant/components/device_tracker/cisco_ios.py", line 50, in __init__
    self.success_init = self._update_info()
  File "/usr/lib/python3.6/site-packages/homeassistant/components/device_tracker/cisco_ios.py", line 70, in _update_info
    string_result = self._get_arp_data()
  File "/usr/lib/python3.6/site-packages/homeassistant/components/device_tracker/cisco_ios.py", line 113, in _get_arp_data
    port=self.port, auto_prompt_reset=False)
  File "/usr/lib/python3.6/site-packages/pexpect/pxssh.py", line 280, in login
    i = self.expect(["(?i)are you sure you want to continue connecting", original_prompt, "(?i)(?:password)|(?:passphrase for key)", "(?i)permission denied", "(?i)terminal type", TIMEOUT, "(?i)connection closed by remote host"], timeout=login_timeout)
  File "/usr/lib/python3.6/site-packages/pexpect/spawnbase.py", line 315, in expect
    timeout, searchwindowsize, async)
  File "/usr/lib/python3.6/site-packages/pexpect/spawnbase.py", line 339, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/lib/python3.6/site-packages/pexpect/expect.py", line 102, in expect_loop
    return self.eof(e)
  File "/usr/lib/python3.6/site-packages/pexpect/expect.py", line 49, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pxssh.pxssh object at 0x740c67b0>
command: /usr/bin/ssh
args: ['/usr/bin/ssh', '-q', '-l', 'sshuser_homeassistant', '192.168.0.1']
searcher: None
buffer (last 100 chars): b''
before (last 100 chars): b''
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 55
child_fd: 16
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration, and usage.
