### ISSUE TITLE
Pauze/resume not working

### ISSUE THREAD

**Issue by walter-ve** [home-assistant/home-assistant.github.io#32526]
### Feedback

Wallbox is charging, try to pauze/resume via Home Assitant and I get an authentication error.  
But I would guess it is an issue in required access rights.  I can set the Power Limit from HA.  
Is this something missing in the documentation.
note: I have a OCPP active (for reimbursing charging cost from my employer via Nexxtmove).

Details on the error below.  

 File "/usr/src/homeassistant/homeassistant/components/wallbox/coordinator.py", line 86, in require_authentication
    raise ConnectionError from wallbox_connection_error

and some more: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/wallbox/coordinator.py", line 82, in require_authentication
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/wallbox/coordinator.py", line 200, in _pause_charger
    self._wallbox.pauseChargingSession(self._station)
  File "/usr/local/lib/python3.12/site-packages/wallbox/wallbox.py", line 142, in pauseChargingSession
    raise (err)
  File "/usr/local/lib/python3.12/site-packages/wallbox/wallbox.py", line 140, in pauseChargingSession
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wall-box.com/v3/chargers/110xxxx/remote-action
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2542, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2579, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 971, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1043, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/wallbox/switch.py", line 81, in async_turn_off
    await self.coordinator.async_pause_charger(True)
  File "/usr/src/homeassistant/homeassistant/components/wallbox/coordinator.py", line 206, in async_pause_charger
    await self.hass.async_add_executor_job(self._pause_charger, pause)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/wallbox/coordinator.py", line 86, in require_authentication
    raise ConnectionError from wallbox_connection_error
ConnectionError

### URL

https://www.home-assistant.io/integrations/wallbox/

### Version

2024.4.4

**Comment by frenck** [comment]
Hi there @walter-ve 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. The UI should not error but instead, guide you through the processes. Please report issues with integration here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by walter-ve** [comment]
Hi Frenck,

Thanks for the feedback.

Actually it is a documentation issue.
I just found in the wallbox doc that the Pauze/resume is not working 
with OCPP active.
https://support.wallbox.com/en/knowledge-base/ocpp-activation-and-setup-guide/
I think we should add in the documentation that Pauze/resume is not 
working with OCPP active.

Walter

Op 2024-04-29 21:59, schreef Franck Nijhof:

**Comment by frenck** [comment]
> I think we should add in the documentation that Pauze/resume is not
working with OCPP active.

I disagree. The integration should handle it properly and most certainly not throw exceptions.
