### ISSUE TITLE
Room requirement For some models of Shark IQ Robots

### ISSUE THREAD

**Issue by lishan89uc** [home-assistant/home-assistant.github.io#32573]
### Feedback

Troubleshooting:
Since 2024.5.0, on some models of Shark IQ vacuum robots you need to have at least 1 room set in the app. 

### URL

https://www.home-assistant.io/integrations/sharkiq/

### Version

2024.5.0

### Additional information

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 892, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1359, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1009, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1071, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sharkiq/vacuum.py", line 275, in extra_state_attributes
    ATTR_ROOMS: self.available_rooms,
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sharkiq/vacuum.py", line 265, in available_rooms
    return self.sharkiq.get_room_list()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sharkiq/sharkiq.py", line 400, in get_room_list
    return self._get_device_room_list()['rooms']
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sharkiq/sharkiq.py", line 390, in _get_device_room_list
    split = room_list.split(':')
            ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by funkybunch** [comment]
@lishan89uc This is not the correct repository to report integration issues.  Please report issues with functionality to [homeassistant/core](https://github.com/home-assistant/core).  This repo is for the documentation site.

However, I believe we already have another issue documenting this.  Please review [#116670](https://github.com/home-assistant/core/issues/116670) and if your issue is different, please open another issue on the core repo.  Closing this issue as reported incorrectly.

**Comment by funkybunch** [comment]
@home-assistant close
