### ISSUE TITLE
edimax SmartPlug Python execption

### ISSUE THREAD

**Issue by matzedd** [home-assistant/home-assistant.github.io#3271]
Since firmware upgrade to version 2.04 hass.io can't connect to my Edimax SmartPlugs SP-1101W switches.
Error messages found as follows:
```
2017-08-28 23:05:32 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.edimax2 fails
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 225, in async_update_ha_state
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/asyncio/futures.py", line 331, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/switch/edimax.py", line 97, in update
    self._state = self.smartplug.state == 'ON'
  File "/usr/lib/python3.6/site-packages/pyedimax/smartplug.py", line 172, in state
    raise Exception("Failed to communicate with SmartPlug")
Exception: Failed to communicate with SmartPlug
2017-08-28 23:05:32 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.edimax1 fails
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 225, in async_update_ha_state
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/asyncio/futures.py", line 331, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/switch/edimax.py", line 97, in update
    self._state = self.smartplug.state == 'ON'
  File "/usr/lib/python3.6/site-packages/pyedimax/smartplug.py", line 172, in state
    raise Exception("Failed to communicate with SmartPlug")
Exception: Failed to communicate with SmartPlug
2017-08-28 23:05:33 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.edimax3 fails
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 225, in async_update_ha_state
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/asyncio/futures.py", line 331, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/switch/edimax.py", line 97, in update
    self._state = self.smartplug.state == 'ON'
  File "/usr/lib/python3.6/site-packages/pyedimax/smartplug.py", line 172, in state
    raise Exception("Failed to communicate with SmartPlug")
Exception: Failed to communicate with SmartPlug
```

What could be the reason? From the EdiLife App I can access the devices. PW doublechecked.

HASS config:
```
core-ssh:/config# cat switches.yaml
### switches.yaml
- platform: edimax
  host: 192.168.133.119
  username: !secret switch_edimax_user
  password: !secret switch_edimax_password
  name: edimax1
- platform: edimax
  host: edimax2
  username: !secret switch_edimax_user
  password: !secret switch_edimax_password
  name: edimax2
- platform: edimax
  host: edimax3
  username: !secret switch_edimax_user
  password: !secret switch_edimax_password
  name: edimax3
```

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration, and usage.
