### ISSUE TITLE
Failed to set up: Check the logs

### ISSUE THREAD

**Issue by ploughansen** [home-assistant/home-assistant.github.io#34828]
### Feedback

I get the following error when I try to setup the integration:

```
Log details (ERROR)
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 21:49:49 (2 occurrences)
Last logged: 21:56:34

Error setting up entry my_username for touchline_sl
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/touchline_sl/__init__.py", line 29, in async_setup_entry
    TouchlineSLModuleCoordinator(hass, module) for module in await account.modules()
                                                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pytouchlinesl/touchlinesl.py", line 66, in modules
    data = await self._client.modules()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pytouchlinesl/client/client.py", line 98, in modules
    return [AccountModuleModel(**m) for m in resp]
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AccountModuleModel
tag
  none is not an allowed value (type=type_error.none.not_allowed)
```

I am 1000% sure the username and password is correct, but other than that, I have no idea what to make of the error?

### URL

https://www.home-assistant.io/integrations/touchline_sl/

### Version

2024.9.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
