### ISSUE TITLE
File integaration: wrong example malicious `'`

### ISSUE THREAD

**Issue by LuckyTurtleDev** [home-assistant/home-assistant.github.io#35961]
### Feedback

the example configuration show: Value template: `'{{ value.split(",")[1] }}'`.
i used the expression `'{{ value.split("=")[1] }}'` for the following input (value has changed between `cat` and error message):
```
54 01 4b 46 7f ff 0c 10 fd : crc=fd YES
54 01 4b 46 7f ff 0c 10 fd t=21250
```
and i get the  error `ValueError: invalid literal for int() with base 10: "'21250'"`.
If you take a look at the value you can see that the `'` at the start and end, which create a convert error.
Removing the `'` from the template fix the issue.

So i think the doc should be as follow instead:
Value template: `{{ value.split(",")[1] }}`

same for "Unit of measurement"

### URL

https://www.home-assistant.io/integrations/file#entries-as-csv

### Version

2024.11.3

### Additional information

```
homeassistant  | 2024-11-24 21:53:51.422 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 659, in state
homeassistant  |     numerical_value = int(value)
homeassistant  |                       ^^^^^^^^^^
homeassistant  | ValueError: invalid literal for int() with base 10: "'21250'"
homeassistant  |
homeassistant  | During handling of the above exception, another exception occurred:
homeassistant  |
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 662, in state
homeassistant  |     numerical_value = float(value)
homeassistant  |                       ^^^^^^^^^^^^
homeassistant  | ValueError: could not convert string to float: "'21250'"
homeassistant  |
homeassistant  | The above exception was the direct cause of the following exception:
homeassistant  |
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1046, in _async_update_entity_states
homeassistant  |     await entity.async_update_ha_state(True)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 962, in async_update_ha_state
homeassistant  |     self._async_write_ha_state()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
homeassistant  |     self.__async_calculate_state()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1069, in __async_calculate_state
homeassistant  |     state = self._stringify_state(available)
homeassistant  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in _stringify_state
homeassistant  |     if (state := self.state) is None:
homeassistant  |                  ^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 666, in state
homeassistant  |     raise ValueError(
homeassistant  | ValueError: Sensor sensor.file has device class 'None', state class 'None' unit '"°C"' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: ''21250'' (<class 'str'>)
```

**Comment by LuckyTurtleDev** [comment]
still relevant

**Comment by frenck** [comment]
Thanks for sharing this @LuckyTurtleDev ❤ 

Addressed this feedback in #38289

../Frenck
