### ISSUE TITLE
myusps.USPSError: expired session

### ISSUE THREAD

**Issue by 5310H** [home-assistant/home-assistant.github.io#3775]
Hi;
Started getting myusps.USPSError: expired session message this morning.  It worked fine yesterday.  Startup log also shows an error with login authentication.  I double checked username and password, both in configuration.yaml and on USPS.com site. They are correct.  Any ideas what going on? 

5310 (newbie)

**Comment by 5310H** [comment]
Did something change yesterday?
Here's my log of the error.
2017-10-25 11:21:31 ERROR (MainThread) [homeassistant.components.sensor] Error on device update!
Traceback (most recent call last):
  File "/usr/local/homeassistant/lib/python3.4/site-packages/myusps/__init__.py", line 204, in wrapped
    return function(*args)
  File "/usr/local/homeassistant/lib/python3.4/site-packages/myusps/__init__.py", line 234, in get_packages
    response = _get_dashboard(session)
  File "/usr/local/homeassistant/lib/python3.4/site-packages/myusps/__init__.py", line 195, in _get_dashboard
    raise USPSError('expired session')
myusps.USPSError: expired session

**Comment by arsaboo** [comment]
Please open issues against the main repo. This USPS issue has already been logged, so you can close this one.

**Comment by 5310H** [comment]
Thanks. What was the Issue #?

**Comment by arsaboo** [comment]
https://github.com/home-assistant/home-assistant/issues/9143#issuecomment-339365735
