### ISSUE TITLE
WeMo connection issue

### ISSUE THREAD

**Issue by ebugakov** [home-assistant/home-assistant.github.io#4203]
Hi! I'm trying to connect my WeMo infrastructure (Light Switch, Link and power switch) to my freshly installed hassie and faced with the error:

```
2017-12-12 15:09:58 ERROR (MainThread) [homeassistant.setup] Error during setup of component wemo
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 193, in _async_setup_component
    component.setup, hass, processed_config)
  File "/usr/lib/python3.6/asyncio/futures.py", line 331, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/wemo.py", line 82, in setup
    devices = [(device.host, device) for device in pywemo.discover_devices()]
  File "/usr/lib/python3.6/site-packages/pywemo/discovery.py", line 20, in discover_devices
    ssdp_entries = ssdp.scan(st, max_entries=max_devices, match_mac=match_mac)
  File "/usr/lib/python3.6/site-packages/pywemo/ssdp.py", line 242, in scan
    response = sock.recv(1024).decode("UTF-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 0: invalid continuation byte
```

Can't see any issues in WeMo devices configuration:

```
<device>
<deviceType>urn:Belkin:device:lightswitch:1</deviceType>
<friendlyName>WeMo Light Entrance</friendlyName>
<manufacturer>Belkin International Inc.</manufacturer>
<manufacturerURL>http://www.belkin.com</manufacturerURL>
<modelDescription>Belkin Plugin Socket 1.0</modelDescription>
<modelName>LightSwitch</modelName>
<modelNumber>1.0</modelNumber>
<modelURL>http://www.belkin.com/plugin/</modelURL>
<serialNumber>xxxxx</serialNumber>
<UDN>uuid:Lightswitch-1_0-221548K1300B01</UDN>
<UPC>123456789</UPC>
<macAddress>xxxx</macAddress>
<firmwareVersion>WeMo_WW_2.00.10966.PVT-OWRT-LS</firmwareVersion>
<iconVersion>0|49154</iconVersion>
<binaryState>0</binaryState>
```

could you please check what could cause the issue?

thanks!

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration, and usage.
