### ISSUE TITLE
Nest Thermostat - Authentication Issue

### ISSUE THREAD

**Issue by josephtpeterson** [home-assistant/home-assistant.github.io#4938]
After rebuilding my HA server, my nest thermostat will not authenticate. I click the request authentication, receive a pin, and after confirm nothing happens. I receive the below warning in the log. I also created a new nest product, with the same failures.

Thank you in advance for any and all assistance.

-Joe

Device: Raspberry Pi 3
Home Assistant: 0.65.5
Hass.io Supervisor: 0.98
Host System:
type: ResinOS (GNU/Linux)
Host Controller: 1.3
                     
Traceback (most recent call last): File "/usr/lib/python3.6/site-packages/homeassistant/core.py", line 1006, in _event_to_service_call await service_handler.func(service_call) File "/usr/lib/python3.6/site-packages/homeassistant/components/configurator.py", line 224, in async_handle_service_call call.data.get(ATTR_FIELDS, {})) File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__ yield self # This tells Task to wait for completion. File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup future.result() File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result raise self._exception File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run result = self.fn(*self.args, **self.kwargs) File "/usr/lib/python3.6/site-packages/homeassistant/components/nest.py", line 67, in nest_configuration_callback setup_nest(hass, nest, config, pin=pin) File "/usr/lib/python3.6/site-packages/homeassistant/components/nest.py", line 85, in setup_nest nest.request_token(pin) File "/usr/lib/python3.6/site-packages/nest/nest.py", line 1551, in request_token self._session.auth.login() File "/usr/lib/python3.6/site-packages/nest/nest.py", line 138, in login response = post(ACCESS_TOKEN_URL, data=data, headers=headers) File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 555, in post return self.request('POST', url, data=data, json=json, **kwargs) File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 508, in request resp = self.send(prep, **send_kwargs) File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 618, in send r = adapter.send(request, **kwargs) File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 508, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.home.nest.com', port=443): Max retries exceeded with url: /oauth2/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x739cbaf0>: Failed to establish a new connection: [Errno -3] Try again',))

**Comment by josephtpeterson** [comment]
Closing issue, I opened it in the wrong thread place.
