### ISSUE TITLE
credits_generator no longer works

### ISSUE THREAD

**Issue by fabaff** [home-assistant/home-assistant.github.io#5479]
To fix #4703 and to update the [credits](https://www.home-assistant.io/developers/credits) page the `credits_generator` is the helper script. But now I end up with a bunch of server errors.

```bash
[...]
Got error when get user details for xyz { Error: connect ETIMEDOUT 192.30.253.117:443
    at module.exports.sendError (/home/test/Documents/repos/home-assistant.github.io/credits_generator/node_modules/github/lib/index.js:838:19)
    at /home/fab/Documents/repos/home-assistant.github.io/credits_generator/node_modules/github/lib/index.js:849:29
    at callCallback (/home/test/Documents/repos/home-assistant.github.io/credits_generator/node_modules/github/lib/index.js:713:17)
    at ClientRequest.<anonymous> (/home/test/Documents/repos/home-assistant.github.io/credits_generator/node_modules/github/lib/index.js:791:17)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
  defaultMessage: 'Internal Server Error',
  message: 'connect ETIMEDOUT 192.30.253.117:443',
  code: '500',
  status: 'Internal Server Error',
  headers: undefined }
```

My limit seems fine `Rate limits: 4976/5000 (remaining/limit)`.

**Comment by balloob** [comment]
Was able to run it in 4914f0eff5

**Comment by robbiet480** [comment]
@fabaff A 500 would mean GitHub was having issues at the time you tried to run it, gonna close this issue, feel free to reopen ofc.
