### ISSUE TITLE
Homekit Controller Does Not Work with iDevices Switch

### ISSUE THREAD

**Issue by kdubmisc** [home-assistant/home-assistant.github.io#5491]
I'm not able to get the homekit controller to work for iDevices after I entered the HomeKit ID.  I for sure removed from homekit since it is the requirement that only one device can be associated to the accessory.

When I used adding iHome ISP8 switch, it works.  I see HA UI show the switch panel for iHome ISP8.  I'm also able to control if via HomeKit iPhone.  So, I'm thinking HomeKit Controller is not compatible w/ iDevices switch.  

Here's my log after I tried adding the iDevice switch after I typed in the homekit ID and hoping to see if anyone ran into the same issue i encountered with iDevices switch:

2018-06-03 21:53:38 INFO (SyncWorker_11) [homeassistant.components.homekit_controller] Setting up Homekit device IDEV0001
2018-06-03 21:53:38 INFO (SyncWorker_10) [homeassistant.components.homekit_controller] Setting up Homekit device Smart Bridge 2
2018-06-03 21:53:38 INFO (SyncWorker_19) [homeassistant.components.homekit_controller] Setting up Homekit device Home Assistant Bridge
2018-06-03 21:54:07 ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting
2018-06-03 21:55:35 DEBUG (MainThread) [homeassistant.components.homekit.accessories] New_state: <state sensor.master_bedroom_temperature=68; unit_of_measurement=°F, friendly_name=Master Bedroom Temperature @ 2018-06-03T21:55:35.247829-07:00>
2018-06-03 21:55:35 DEBUG (SyncWorker_8) [homeassistant.components.homekit.type_sensors] sensor.master_bedroom_temperature: Current temperature set to 20°C
2018-06-03 21:56:28 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall configurator.configure: configure_id=1881863760-3, fields=code=513-83-435>
Traceback (most recent call last):
  File "/usr/lib/python3.6/http/client.py", line 546, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.6/http/client.py", line 513, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/http/client.py", line 563, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.6/http/client.py", line 548, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/configurator.py", line 224, in async_handle_service_call
    call.data.get(ATTR_FIELDS, {}))
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/homekit_controller/__init__.py", line 161, in device_config_callback
    self.accessory_setup()
  File "/usr/lib/python3.6/site-packages/homeassistant/components/homekit_controller/__init__.py", line 112, in accessory_setup
    data = json.loads(response.read().decode())
  File "/usr/lib/python3.6/http/client.py", line 456, in read
    return self._readall_chunked()
  File "/usr/lib/python3.6/http/client.py", line 570, in _readall_chunked
    raise IncompleteRead(b''.join(value))
http.client.IncompleteRead: IncompleteRead(0 bytes read)

**Comment by njakobsen** [comment]
I am very new to this and I have the same problem with this device. I wonder if it's because when you reset it, it loses its wifi connection so you can't actually see it on the network.
