### ISSUE TITLE
Internal error validating code

### ISSUE THREAD

**Issue by erfind** [home-assistant/home-assistant.github.io#6012]
```
2018-08-13 19:32:54 ERROR (MainThread) [homeassistant.components.nest.config_flow] Unexpected error resolving code
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 56, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f80674828>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.home.nest.com', port=443): Max retries exceeded with url: /oauth2/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f80674828>: Failed to establish a new connection: [Errno -3] Try again',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/nest/config_flow.py", line 100, in async_step_link
    tokens = await flow['convert_code'](user_input['code'])
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/nest/local_auth.py", line 38, in resolve_auth_code
    await hass.async_add_job(auth.login)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/nest/nest.py", line 175, in login
    response = post(ACCESS_TOKEN_URL, data=data, headers=headers)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.home.nest.com', port=443): Max retries exceeded with url: /oauth2/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f80674828>: Failed to establish a new connection: [Errno -3] Try again',))
```

**Comment by erfind** [comment]
This happens whenever I try to add a Nest integration.

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration and usage.
