### ISSUE TITLE
Issue with Honeywell Component

### ISSUE THREAD

**Issue by erfind** [home-assistant/home-assistant.github.io#6918]
I'm not sure how to file a bug report for a specific component.  However I'm having issues setting up a Honeywell Thermostat with Home Assistant. The error log is as follows:
```
Wed Oct 17 2018 21:23:05 GMT-0500 (CDT)

Error while setting up platform honeywell
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/climate/honeywell.py", line 63, in setup_platform
    return _setup_round(username, password, config, add_entities)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/climate/honeywell.py", line 75, in _setup_round
    for i, zone in enumerate(zones):
  File "/usr/local/lib/python3.6/site-packages/evohomeclient/__init__.py", line 73, in temperatures
    self._populate_full_data(force_refresh)
  File "/usr/local/lib/python3.6/site-packages/evohomeclient/__init__.py", line 33, in _populate_full_data
    userId = self.user_data['userInfo']['userID']
TypeError: list indices must be integers or slices, not str
```

Could someone point me to the right place to get some help with this?

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration and usage.
