### ISSUE TITLE
Restart from web raises error in log

### ISSUE THREAD

**Issue by brianharwell** [home-assistant/home-assistant.github.io#7337]
When I try to Restart HA from the web interface I see this error in the log...

```
2018-11-02 14:32:51 ERROR (MainThread) [homeassistant.components.hassio.handler] /homeassistant/check return code 500.
2018-11-02 14:32:51 ERROR (MainThread) [homeassistant.components.hassio] Error on Hass.io API:
2018-11-02 14:32:51 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall homeassistant.restart (c:838ec0dc277c47c9a79d01fc49b1c8f9)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1177, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/hassio/__init__.py", line 264, in async_handle_core_service
    error = await async_check_config(hass)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/hassio/__init__.py", line 147, in async_check_config
    if result['result'] == "error":
UnboundLocalError: local variable 'result' referenced before assignment

```

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration and usage.

**Comment by brianharwell** [comment]
My bad! Thanks
