### ISSUE TITLE
Alarm Panel Card (lovelace) fails for codes entered via keyboard

### ISSUE THREAD

**Issue by meaniegreenie** [home-assistant/home-assistant.github.io#8293]
Using the Alarm Panel Card to control Elk M1 alarm in HASS 0.86 correctly arms/disarms the alarm when code is entered using the on-screen buttons.   However, the code input allows users to type in values as well.  When this is done, the arm/disarm does not occur and HASS logs the following error.  
Since the log seems to indicate that no string was passed to the alarm, I suspect this component is not sending a value obtained from the text field, but dynamically creates the sent code based each click of an on-screen button.

NOTE: I have replaced the specific base directory with the following text: "<HASS_DIR>"

2019-01-26 10:22:15 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "<HASS_DIR>/hass/env/lib/python3.5/site-packages/homeassistant/helpers/service.py", line 287, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "<HASS_DIR>/hass/env/lib/python3.5/site-packages/homeassistant/components/alarm_control_panel/elkm1.py", line 185, in async_alarm_arm_home
    self._element.arm(ArmLevel.ARMED_STAY.value, int(code))
ValueError: invalid literal for int() with base 10: ''

**Comment by meaniegreenie** [comment]
It appears that I have created this issue in the wrong location.  I didn't realize this was the "documentation" part of Home Assistant. 
Please advise as to whether the issue can be transferred to the code repo or if I should create a separate issue.
Sorry for the error.

**Comment by meaniegreenie** [comment]
Will close this issue and open correctly formatted one in code repo.
